/**
 * ─── DEMO DATASET ──────────────────────────────────────────────────────────────
 * Constant demo data for every interface of the app, written as the database
 * rows the loaders read (snake_case), so the demo exercises the exact same code
 * paths as production.
 *
 * The numbers are generated by a seeded pseudo-random walk, so they are the SAME
 * on every load, and they hang together: pistolet indexes follow one another from
 * brigade to brigade, cuves are refilled by fuel purchases when they run low,
 * brigade takings are split between cash, client bons and TPE, and every part's
 * sales, purchases, expenses and salaries feed its own caisse. Dates are anchored
 * on "today" so the current month is always full of activity.
 * ──────────────────────────────────────────────────────────────────────────────
 */
import { interfacesForModule, ModuleKey } from '../bizConfig';
import { getDefaultPermissions, ALL_MODULES } from '../permissionDefaults';

// ─── Demo accounts (quick access on the login page) ────────────────────────────
export interface DemoAccount {
  userId: string;
  role: 'admin' | 'pompiste' | 'chef_brigade' | 'gerant' | 'magasin' | 'module_worker';
  name: string;
  username: string;
  email: string;
  password: string;
  /** Row of the worker table (pompistes, gerants, module_workers…). */
  workerId?: string;
  moduleKey?: ModuleKey;
  /** Short caption shown on the quick-access button. */
  label: string;
}

export const DEMO_PASSWORD = 'demo123';

export const DEMO_ACCOUNTS: DemoAccount[] = [
  { userId: 'u-admin', role: 'admin', name: 'Youcef Admin', username: 'admin', email: 'admin@demo.dz', password: DEMO_PASSWORD, label: 'Administrateur' },
  { userId: 'u-gerant', role: 'gerant', name: 'Nadia Belkacem', username: 'gerant', email: 'gerant@demo.dz', password: DEMO_PASSWORD, workerId: 'ger-01', label: 'Gérant' },
  { userId: 'u-chef', role: 'chef_brigade', name: 'Karim Benali', username: 'chef', email: 'chef@demo.dz', password: DEMO_PASSWORD, workerId: 'chf-01', label: 'Chef de brigade' },
  { userId: 'u-pompiste', role: 'pompiste', name: 'Amine Saidi', username: 'pompiste', email: 'pompiste@demo.dz', password: DEMO_PASSWORD, workerId: 'pmp-01', label: 'Pompiste' },
  { userId: 'u-magasin', role: 'magasin', name: 'Lamia Rahmani', username: 'magasin', email: 'magasin@demo.dz', password: DEMO_PASSWORD, workerId: 'mag-01', label: 'Employé magasin' },
  { userId: 'u-restaurant', role: 'module_worker', name: 'Sofiane Mansouri', username: 'restaurant', email: 'restaurant@demo.dz', password: DEMO_PASSWORD, workerId: 'rs-wrk-01', moduleKey: 'restaurant', label: 'Restaurant' },
  { userId: 'u-cafeteria', role: 'module_worker', name: 'Imane Cherif', username: 'cafeteria', email: 'cafeteria@demo.dz', password: DEMO_PASSWORD, workerId: 'cf-wrk-01', moduleKey: 'cafeteria', label: 'Cafétéria' },
  { userId: 'u-lavage', role: 'module_worker', name: 'Bilal Kaci', username: 'lavage', email: 'lavage@demo.dz', password: DEMO_PASSWORD, workerId: 'lv-wrk-01', moduleKey: 'lavage', label: 'Lavage & Vidange' },
];

// ─── Deterministic helpers ─────────────────────────────────────────────────────
let _seed = 20260930;
function rnd(): number {
  _seed |= 0; _seed = (_seed + 0x6D2B79F5) | 0;
  let t = Math.imul(_seed ^ (_seed >>> 15), 1 | _seed);
  t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
  return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
}
const ri = (a: number, b: number) => Math.floor(a + rnd() * (b - a + 1));
const rf = (a: number, b: number) => a + rnd() * (b - a);
const pick = <T,>(arr: T[]): T => arr[Math.floor(rnd() * arr.length)];
const chance = (p: number) => rnd() < p;
const r2 = (n: number) => Math.round(n * 100) / 100;
const pad = (n: number, w = 3) => String(n).padStart(w, '0');
function sample<T>(arr: T[], n: number): T[] {
  const copy = [...arr]; const out: T[] = [];
  while (out.length < n && copy.length) out.push(copy.splice(Math.floor(rnd() * copy.length), 1)[0]);
  return out;
}

let NOW = new Date();
/** A moment `daysAgo` days before today, at local `hour:min`. */
function at(daysAgo: number, hour = 9, min = 0): Date {
  const d = new Date(NOW.getFullYear(), NOW.getMonth(), NOW.getDate() - daysAgo, hour, min, 0, 0);
  return d;
}
const iso = (d: Date) => d.toISOString();
const ymd = (d: Date) =>
  `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`;
const hhmm = (d: Date) => `${String(d.getHours()).padStart(2, '0')}:${String(d.getMinutes()).padStart(2, '0')}`;
const monthKey = (d: Date) => `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}`;

const DAYS = 45;           // history depth for the carburant part
const BIZ_DAYS = 35;       // history depth for the business parts
const ADMIN_NAME = 'Youcef Admin';

const CAISSE = 'CAISSE';
const CAISSE_PART: Record<string, string> = {
  carburant: 'CAISSE_CARBURANT', restaurant: 'CAISSE_RESTAURANT',
  cafeteria: 'CAISSE_CAFETERIA', lavage: 'CAISSE_LAVAGE',
};

// ═══════════════════════════════════════════════════════════════════════════════
export function buildSeed(): Record<string, any[]> {
  _seed = 20260930;
  NOW = new Date();
  const T: Record<string, any[]> = {};
  const push = (tbl: string, row: any) => { (T[tbl] ||= []).push(row); return row; };

  // ─── Settings ───────────────────────────────────────────────────────────────
  const fuelPrices = { ESSENCE: 45.62, SUPER: 47.62, GASOIL: 29.01, DIESEL: 29.01, GPL: 9 };
  const fuelBuyPrices = { ESSENCE: 40.5, SUPER: 42.5, GASOIL: 25.6, DIESEL: 25.6, GPL: 6.9 };
  const expenseCategories = ['Salaires', 'Entretien', 'Électricité', 'Eau', 'Loyer', 'Impôts', 'Transport', 'Fournitures', 'Téléphone & Internet', 'Divers'];
  push('station_settings', {
    id: 'settings-1',
    name: 'Station Altech — El Hamiz',
    logo_url: null,
    address: 'RN 5, Zone industrielle El Hamiz, Dar El Beïda, Alger',
    phone: '023 85 42 10',
    email: 'contact@altech-station.dz',
    fiscal_id: '000216098765432',
    rc: '16/00-1234567B21',
    fuel_prices: fuelPrices,
    fuel_buy_prices: fuelBuyPrices,
    conversion_tables: {},
    product_categories: ['Lubrifiants', 'Accessoires', 'Entretien auto', 'Boissons', 'Snacks', 'Hygiène'],
    expense_categories: expenseCategories,
    product_units: ['Pièce', 'L', 'Kg', 'Boîte', 'Carton', 'Bidon'],
    decalage_positif_actif: true,
    decalage_negatif_actif: true,
    decalage_positif_seuil: 500,
    decalage_negatif_seuil: 500,
    created_at: iso(at(400)),
  });

  push('admin_profiles', {
    id: 'u-admin', name: ADMIN_NAME, username: 'admin', email: 'admin@demo.dz', role: 'admin',
    avatar_url: null, phone: '0550 12 34 56', created_at: iso(at(400)),
  });

  // ─── Bank accounts ──────────────────────────────────────────────────────────
  const banks = [
    { id: 'ba-01', name: 'BNA — Compte courant', account_number: '001 00456 0300012345 67', initial_balance: 2_450_000, notes: 'Compte principal de la station' },
    { id: 'ba-02', name: 'CPA — Compte TPE / TAG', account_number: '004 00123 4500098765 12', initial_balance: 380_000, notes: 'Encaissements cartes CIB, Edahabia et TAG Naftal' },
    { id: 'ba-03', name: 'BADR — Épargne', account_number: '003 00987 6500043210 88', initial_balance: 1_200_000, notes: 'Réserve' },
    { id: 'ba-04', name: 'CCP Algérie Poste', account_number: '0012345678 clé 90', initial_balance: 145_000, notes: '' },
  ];
  banks.forEach((b, i) => push('bank_accounts', { ...b, balance: b.initial_balance, created_at: iso(at(380 - i)) }));
  const tx = (row: any) => push('treasury_transactions', {
    description: null, account_from: null, account_to: null, ref_type: null, ref_id: null,
    cheque_number: null, bordereau_number: null, created_by: ADMIN_NAME, ...row,
    created_at: row.created_at || row.date,
  });
  let txN = 0;
  const txId = () => `trx-${pad(++txN, 5)}`;

  // ─── Tanks, tracks, pumps, pistolets ────────────────────────────────────────
  const tanks = [
    { id: 'tank-01', name: 'Cuve 1 — Gasoil', type: 'GASOIL', capacity: 40000 },
    { id: 'tank-02', name: 'Cuve 2 — Gasoil', type: 'GASOIL', capacity: 40000 },
    { id: 'tank-03', name: 'Cuve 3 — Essence', type: 'ESSENCE', capacity: 30000 },
    { id: 'tank-04', name: 'Cuve 4 — Super', type: 'SUPER', capacity: 20000 },
    { id: 'tank-05', name: 'Cuve 5 — GPL', type: 'GPL', capacity: 15000 },
  ];
  const tankLevel: Record<string, number> = {};
  tanks.forEach(t => { tankLevel[t.id] = Math.round(t.capacity * rf(0.55, 0.8)); });
  const degreesOf = (tankId: string, liters: number) => {
    const t = tanks.find(x => x.id === tankId)!;
    return r2((liters / t.capacity) * 250);
  };

  ['Piste 1', 'Piste 2', 'Piste 3'].forEach((name, i) =>
    push('tracks', { id: `trk-0${i + 1}`, name, created_at: iso(at(390)) }));

  const pumpDefs = [
    { id: 'pump-01', number: 'P1', name: 'Pompe 1', nozzles: ['tank-01', 'tank-03'] },
    { id: 'pump-02', number: 'P2', name: 'Pompe 2', nozzles: ['tank-02', 'tank-03'] },
    { id: 'pump-03', number: 'P3', name: 'Pompe 3', nozzles: ['tank-01', 'tank-04'] },
    { id: 'pump-04', number: 'P4', name: 'Pompe 4', nozzles: ['tank-02', 'tank-04'] },
    { id: 'pump-05', number: 'P5', name: 'Pompe 5 — GPL', nozzles: ['tank-05', 'tank-05'] },
    { id: 'pump-06', number: 'P6', name: 'Pompe 6 — Poids lourds', nozzles: ['tank-01', 'tank-02'] },
  ];
  const nozzles: { id: string; pumpId: string; name: string; tankId: string; type: string; start: number }[] = [];
  pumpDefs.forEach((p, pi) => p.nozzles.forEach((tankId, ni) => {
    const tank = tanks.find(t => t.id === tankId)!;
    nozzles.push({
      id: `noz-${pad(pi * 2 + ni + 1, 2)}`, pumpId: p.id,
      name: `Pistolet ${ni + 1} — ${tank.type}`, tankId, type: tank.type,
      start: ri(80_000, 420_000) + r2(rnd()),
    });
  }));
  const nozzleIdx: Record<string, number> = {};
  nozzles.forEach(n => { nozzleIdx[n.id] = n.start; });

  // ─── People ─────────────────────────────────────────────────────────────────
  const pompisteNames = [
    'Amine Saidi', 'Walid Hamidi', 'Yacine Boukhari', 'Hichem Ferhat', 'Riad Meziane',
    'Nabil Zerrouki', 'Farid Lounis', 'Mehdi Taleb', 'Omar Djebbar', 'Sid Ali Kherbouche',
    'Anis Belaid', 'Toufik Rezig',
  ];
  const chefNames = ['Karim Benali', 'Mourad Haddad', 'Samir Boudiaf'];
  const gerantNames = ['Nadia Belkacem', 'Rachid Ouali'];
  const magasinNames = ['Lamia Rahmani', 'Hakim Slimani', 'Sara Bensalem'];
  const phone = () => `0${pick(['5', '6', '7'])}${ri(10, 99)} ${ri(10, 99)} ${ri(10, 99)} ${ri(10, 99)}`;
  const cin = () => `${ri(100000000, 999999999)}${ri(100000000, 999999999)}`;
  const addr = () => `${ri(1, 120)} ${pick(['Cité 500 logts', 'Rue Larbi Ben Mhidi', 'Cité AADL', 'Hai El Djorf', 'Rue des Frères Bouadou', 'Bd Colonel Amirouche'])}, ${pick(['Dar El Beïda', 'Bab Ezzouar', 'Rouiba', 'Reghaïa', 'El Hamiz', 'Bordj El Kiffan'])}`;

  const workerBase = (name: string, i: number, extra: any = {}) => ({
    name, phone: phone(), email: `${name.split(' ')[0].toLowerCase()}.${i}@altech-station.dz`, cin: cin(), address: addr(),
    photo_url: null, status: 'Actif', has_access: false, username: null, auth_user_id: null,
    permissions: {}, hire_date: ymd(at(ri(120, 900))), created_at: iso(at(ri(120, 900))), ...extra,
  });

  const pompistes = pompisteNames.map((name, i) => push('pompistes', {
    id: `pmp-${pad(i + 1, 2)}`, ...workerBase(name, i),
    track_id: `trk-0${(i % 3) + 1}`, chef_id: `chf-0${(i % 3) + 1}`,
    base_salary: pick([38000, 40000, 42000, 45000]), salary_type: 'mois', work_days: null,
    cnas_date: ymd(at(ri(100, 700))),
  }));
  const chefs = chefNames.map((name, i) => push('brigade_chefs', {
    id: `chf-${pad(i + 1, 2)}`, ...workerBase(name, i + 20), base_salary: pick([55000, 58000, 60000]),
  }));
  const gerants = gerantNames.map((name, i) => push('gerants', {
    id: `ger-${pad(i + 1, 2)}`, ...workerBase(name, i + 30), base_salary: pick([75000, 85000]),
    salary_type: 'mois', work_days: null, cnas_date: ymd(at(ri(200, 800))),
  }));
  const magasins = magasinNames.map((name, i) => push('magasin_workers', {
    id: `mag-${pad(i + 1, 2)}`, ...workerBase(name, i + 40), base_salary: pick([35000, 38000]),
    salary_type: 'mois', work_days: null, cnas_date: ymd(at(ri(100, 600))),
  }));
  pompistes.forEach((p, i) => push('chef_pompiste_assignments', { chef_id: `chf-0${(i % 3) + 1}`, pompiste_id: p.id }));

  // Accounts wired to worker rows.
  const fullPerm = { voir: true, creer: true, modifier: true, supprimer: true, imprimer: true, exporter: true, scanner: true, generer: true };
  const accountFor = (tbl: any[], id: string, role: 'pompiste' | 'chef_brigade' | 'gerant' | 'magasin') => {
    const acc = DEMO_ACCOUNTS.find(a => a.workerId === id)!;
    const row = tbl.find(r => r.id === id);
    const perms = getDefaultPermissions(role);
    perms['Tableau de bord'] = { ...perms['Tableau de bord'], voir: true };
    if (role === 'gerant') {
      ALL_MODULES.forEach(m => { if (!perms[m.id]?.voir) perms[m.id] = { ...fullPerm, supprimer: false }; });
      perms['Statistiques'] = { ...fullPerm, supprimer: false };
      perms['Rapports'] = { ...fullPerm, supprimer: false };
    }
    if (role === 'magasin') {
      ['Clients', 'Dépenses', 'Inventaires'].forEach(k => { perms[k] = { ...fullPerm, supprimer: false }; });
    }
    Object.assign(row, {
      has_access: true, username: acc.username, email: acc.email, auth_user_id: acc.userId, permissions: perms,
    });
  };
  accountFor(pompistes, 'pmp-01', 'pompiste');
  accountFor(chefs, 'chf-01', 'chef_brigade');
  accountFor(gerants, 'ger-01', 'gerant');
  accountFor(magasins, 'mag-01', 'magasin');

  // Permission templates.
  (['pompiste', 'chef_brigade', 'gerant', 'magasin'] as const).forEach((role, i) => push('permission_templates', {
    id: `tpl-0${i + 1}`,
    name: { pompiste: 'Pompiste standard', chef_brigade: 'Chef de brigade', gerant: 'Gérant complet', magasin: 'Magasinier' }[role],
    role, permissions: getDefaultPermissions(role), created_at: iso(at(300 - i)),
  }));

  // Payroll of the fuel staff.
  let payN = 0; let acoN = 0; let absN = 0;
  const payroll = (worker: any, type: string) => {
    for (let m = 2; m >= 1; m--) {
      const d = new Date(NOW.getFullYear(), NOW.getMonth() - m + 1, 1, 10);
      const acompte = chance(0.5) ? pick([3000, 5000, 8000, 10000]) : 0;
      const absence = chance(0.25) ? pick([1500, 2000, 3000]) : 0;
      if (acompte) push('worker_acomptes', {
        id: `aco-${pad(++acoN, 4)}`, worker_id: worker.id, worker_type: type,
        date: ymd(new Date(d.getFullYear(), d.getMonth() - 1, ri(8, 20))), amount: acompte,
        description: 'Avance sur salaire', is_paid: true, month_paid: monthKey(new Date(d.getFullYear(), d.getMonth() - 1, 1)),
        created_at: iso(d),
      });
      if (absence) push('worker_absences', {
        id: `abs-${pad(++absN, 4)}`, worker_id: worker.id, worker_type: type,
        date: ymd(new Date(d.getFullYear(), d.getMonth() - 1, ri(3, 25))), cost: absence,
        description: pick(['Absence non justifiée', 'Retard répété', 'Congé sans solde']), is_paid: true,
        month_paid: monthKey(new Date(d.getFullYear(), d.getMonth() - 1, 1)), created_at: iso(d),
      });
      const base = Number(worker.base_salary) || 0;
      const net = base - acompte - absence;
      push('worker_payment_records', {
        id: `pay-${pad(++payN, 4)}`, worker_id: worker.id, worker_type: type,
        month: monthKey(new Date(d.getFullYear(), d.getMonth() - 1, 1)), base_salary: base,
        total_acomptes: acompte, total_absences: absence, bonus_decalage: 0, retenue_decalage: 0,
        net_salary: net, payment_date: iso(at(Math.max(1, Math.round((NOW.getTime() - d.getTime()) / 864e5)), 11)),
        payment_mode: pick(['ESPÈCES', 'ESPÈCES', 'VIREMENT']), cheque_number: null,
        notes: null, is_paid: true, created_at: iso(d),
      });
    }
    // Current month: an unpaid acompte already handed over.
    if (chance(0.45)) push('worker_acomptes', {
      id: `aco-${pad(++acoN, 4)}`, worker_id: worker.id, worker_type: type,
      date: ymd(at(ri(1, Math.max(1, NOW.getDate() - 1)))), amount: pick([2000, 4000, 5000, 6000]),
      description: 'Acompte du mois', is_paid: false, month_paid: null, created_at: iso(at(3)),
    });
  };
  pompistes.forEach(p => payroll(p, 'pompiste'));
  chefs.forEach(c => payroll(c, 'chef_brigade'));
  gerants.forEach(g => payroll(g, 'gerant'));
  magasins.forEach(m => payroll(m, 'magasin'));

  // ─── Suppliers ──────────────────────────────────────────────────────────────
  const supplierDefs = [
    { name: 'NAFTAL — District Carburants Alger', type: 'Carburant', contact: 'Service commercial' },
    { name: 'NAFTAL — GPL Centre', type: 'Carburant', contact: 'M. Bouzid' },
    { name: 'Petrolub Distribution', type: 'Magasin', contact: 'Mme Aït Ahmed' },
    { name: 'Total Lubrifiants Algérie', type: 'Magasin', contact: 'M. Larbi' },
    { name: 'Sarl AutoPièces El Harrach', type: 'Magasin', contact: 'M. Hamza' },
    { name: 'Transport Frères Belhadj', type: 'Carburant', contact: 'Djamel Belhadj' },
  ];
  const suppliers = supplierDefs.map((s, i) => push('suppliers', {
    id: `sup-${pad(i + 1, 2)}`, ref: `FRS-${pad(i + 1, 3)}`, name: s.name, contact: s.contact,
    phone: phone(), email: `contact${i + 1}@fournisseur.dz`, address: addr(),
    balance: 0, total_purchases: 0, nif: `0009${ri(10000000000, 99999999999)}`, nis: `${ri(1000000000, 9999999999)}`,
    article: `${ri(10000000, 99999999)}`, rc: `16/00-${ri(1000000, 9999999)}B${ri(10, 22)}`, type: s.type,
    created_at: iso(at(360 - i)),
  }));

  push('drivers', { id: 'drv-01', name: 'Ahmed Belhadj', status: 'Actif', phone: phone(), email: null, address: addr(), created_at: iso(at(200)) });
  push('drivers', { id: 'drv-02', name: 'Mustapha Kerroum', status: 'Actif', phone: phone(), email: null, address: addr(), created_at: iso(at(190)) });
  push('drivers', { id: 'drv-03', name: 'Lyes Haddadi', status: 'Actif', phone: phone(), email: null, address: addr(), created_at: iso(at(150)) });

  // ─── Clients (carburant) ────────────────────────────────────────────────────
  const clientDefs: [string, 'PARTICULIER' | 'ENTREPRISE' | 'GOUVERNEMENT', 'CASH' | 'CREDIT' | 'ADVANCE'][] = [
    ['Cosider Travaux Publics', 'ENTREPRISE', 'CREDIT'],
    ['ETRHB Haddad — Chantier Rouiba', 'ENTREPRISE', 'CREDIT'],
    ['APC El Hamiz', 'GOUVERNEMENT', 'CREDIT'],
    ['Direction des Travaux Publics Alger', 'GOUVERNEMENT', 'CREDIT'],
    ['Transport Benmansour & Fils', 'ENTREPRISE', 'ADVANCE'],
    ['Sarl Logistique Atlas', 'ENTREPRISE', 'CREDIT'],
    ['Taxi Collectif — Brahim Yousfi', 'PARTICULIER', 'ADVANCE'],
    ['Ambulances Es-Salama', 'ENTREPRISE', 'ADVANCE'],
    ['Eurl BTP Kaci', 'ENTREPRISE', 'CREDIT'],
    ['Sonelgaz Distribution Est Alger', 'GOUVERNEMENT', 'CREDIT'],
    ['Auto-École El Nadjah', 'PARTICULIER', 'ADVANCE'],
    ['Cevital Logistique', 'ENTREPRISE', 'CREDIT'],
    ['Sarl TransMed Frigo', 'ENTREPRISE', 'ADVANCE'],
    ['Hôpital Zmirli — Parc auto', 'GOUVERNEMENT', 'CREDIT'],
    ['Karim Touati (VTC)', 'PARTICULIER', 'ADVANCE'],
    ['Entreprise Bâtiment Ouled Moussa', 'ENTREPRISE', 'CREDIT'],
    ['Société des Eaux SEAAL — Agence Est', 'GOUVERNEMENT', 'CREDIT'],
    ['Transports Scolaires Rouiba', 'ENTREPRISE', 'ADVANCE'],
    ['Mohamed Chaoui', 'PARTICULIER', 'CASH'],
    ['Agence de Location Sahara Cars', 'ENTREPRISE', 'CREDIT'],
    ['Minoterie El Hidhab', 'ENTREPRISE', 'CREDIT'],
    ['Karima Boualem', 'PARTICULIER', 'CASH'],
  ];
  const clients = clientDefs.map(([name, type, mode], i) => push('clients', {
    id: `cli-${pad(i + 1, 2)}`, name, phone: phone(), cin: type === 'PARTICULIER' ? cin() : null,
    email: type === 'PARTICULIER' ? null : `compta${i + 1}@client.dz`, address: addr(),
    contact_person: type === 'PARTICULIER' ? null : pick(['M. Saadi', 'Mme Hamdi', 'M. Rahal', 'Service comptabilité']),
    balance: 0, debt: 0, credit_limit: mode === 'CREDIT' ? pick([300000, 500000, 1000000]) : 0,
    payment_delay: mode === 'CREDIT' ? pick([15, 30, 45, 60]) : 0, type, payment_mode: mode,
    nif: type === 'PARTICULIER' ? null : `0001${ri(10000000000, 99999999999)}`, nis: null, article: null, rc: null,
    advance_balance: 0,
    opening_debt: mode === 'CREDIT' && chance(0.4) ? pick([45000, 80000, 125000, 210000]) : 0,
    opening_advance: 0, opening_date: ymd(at(DAYS + 5)), opening_notes: null,
    created_at: iso(at(DAYS + 10 + i)),
  }));
  const creditClients = clients.filter(c => c.payment_mode !== 'CASH');
  const clientConsumption: Record<string, number> = {};

  // Advance clients start with a recharge.
  let ctN = 0;
  const clientTx = (clientId: string, date: Date, type: 'PAYMENT' | 'RECHARGE', amount: number, mode: string) => {
    const id = `ctx-${pad(++ctN, 4)}`;
    push('client_transactions', {
      id, client_id: clientId, date: iso(date), type, amount, mode,
      receipt_number: mode === 'CHEQUE' ? `CHQ ${ri(1000000, 9999999)}` : `REC-${pad(ctN, 5)}`,
      receipt_photo_url: null, notes: type === 'RECHARGE' ? 'Recharge avance carburant' : 'Règlement de facture',
      created_at: iso(date),
    });
    const client = clients.find(c => c.id === clientId)!;
    tx({
      id: txId(), date: iso(date), kind: 'SALE', amount,
      description: `${type === 'RECHARGE' ? 'Recharge avance client' : 'Règlement client'} — ${client.name} · ${mode === 'ESPECES' ? 'Espèces' : mode === 'CHEQUE' ? 'Chèque' : 'Virement'}`,
      account_to: mode === 'ESPECES' ? CAISSE_PART.carburant : 'ba-01', part: 'carburant',
      ref_type: 'client_payment', ref_id: id,
    });
  };
  clients.filter(c => c.payment_mode === 'ADVANCE').forEach(c => {
    clientTx(c.id, at(DAYS + 2, 10), 'RECHARGE', pick([150000, 200000, 300000, 400000]), pick(['VIREMENT', 'CHEQUE', 'ESPECES']));
  });

  // ─── Brigades ───────────────────────────────────────────────────────────────
  let bN = 0; let jN = 0; let tpeN = 0; let decN = 0; let expN = 0;
  let purN = 0; let dnN = 0;
  const brigadeExpenses: any[] = [];
  const pendingDeliveries: { tankId: string; day: number }[] = [];
  const fuelPurchases: any[] = [];

  const doDelivery = (daysAgo: number, tankId: string) => {
    const tank = tanks.find(t => t.id === tankId)!;
    const liters = Math.round((tank.capacity * 0.9 - tankLevel[tankId]) / 1000) * 1000;
    if (liters < 3000) return;
    const date = at(daysAgo, 7, 30);
    const supplier = tank.type === 'GPL' ? suppliers[1] : suppliers[0];
    const price = fuelBuyPrices[tank.type as keyof typeof fuelBuyPrices];
    const total = r2(liters * price);
    const id = `pur-${pad(++purN, 3)}`;
    const recent = daysAgo <= 6;
    const paid = recent && chance(0.6) ? r2(total * pick([0, 0.5, 0.6])) : total;
    const rest = r2(total - paid);
    const invoiceNumber = `FAC-NFT-${ymd(date).replace(/-/g, '')}-${ri(10, 99)}`;
    const blNumber = `BL-${ri(100000, 999999)}`;
    const payments = paid > 0 ? [{
      id: `ppay-${pad(purN, 3)}`, purchase_id: id, date: iso(at(daysAgo, 11)), amount: paid,
      mode: chance(0.7) ? 'VIREMENT' : 'CHEQUE', cheque_number: null, bordereau_number: `BRD-${ri(10000, 99999)}`,
      account_id: 'ba-01', notes: null, created_at: iso(date),
    }] : [];
    const purchase = push('purchases', {
      id, date: iso(date), supplier_id: supplier.id, invoice_number: invoiceNumber, due_date: ymd(at(daysAgo - 30)),
      driver_id: pick(['drv-01', 'drv-02', 'drv-03']), total, amount_paid: paid, rest,
      status: rest <= 0 ? 'Payé' : paid > 0 ? 'Dette partielle' : 'Dette',
      payment_mode: 'VIREMENT', cheque_number: null, linked_delivery_note_id: null,
      notes: `Livraison ${tank.name}`, type: 'RECEPTION', tva_rate: 0, tva_active: false, tank_id: tankId,
      receipt_photo_url: null, bl_number: blNumber, subtotal: total, tva_amount: 0,
      discount_type: null, discount_value: null, discount_amount: 0,
      appointment_active: rest > 0, appointment_date: rest > 0 ? ymd(at(-ri(3, 15))) : null,
      appointment_amount: rest > 0 ? rest : null, appointment_notes: rest > 0 ? 'Solde à régler par virement' : null,
      appointment_paid: rest <= 0, appointment_paid_at: rest <= 0 ? iso(at(daysAgo, 11)) : null,
      created_at: iso(date),
    });
    push('purchase_items', {
      id: `pit-${pad(purN, 3)}`, purchase_id: id, product_id: null, product_name: `${tank.name} — ${tank.type}`,
      quantity: liters, buy_price: price, selling_price: 0, min_stock: null, unit: 'L', total, tank_id: tankId,
      tva_active: false, tva_rate: 0,
    });
    payments.forEach(p => {
      push('purchase_payments', p);
      tx({
        id: txId(), date: p.date, kind: 'PURCHASE', amount: p.amount,
        description: `Achat carburant n° ${invoiceNumber} — ${supplier.name}`, account_from: p.account_id,
        part: 'carburant', ref_type: 'purchase', ref_id: id, bordereau_number: p.bordereau_number,
      });
    });
    fuelPurchases.push(purchase);
    // Bon de livraison matching the delivery.
    const dnId = `dn-${pad(++dnN, 3)}`;
    push('delivery_notes', {
      id: dnId, date: iso(date), supplier_id: supplier.id, tank_id: tankId, liters, price_per_liter: price,
      status: 'Reçu', total, expiry_date: null, bl_number: blNumber, bl_date: ymd(date), creation_date: iso(date),
      immatriculation: `${ri(10000, 99999)} ${ri(110, 124)} 16`, driver_id: purchase.driver_id, created_at: iso(date),
    });
    push('delivery_note_items', { id: `dni-${pad(dnN, 3)}`, delivery_note_id: dnId, tank_id: tankId, liters, price_per_liter: price, total });
    if (paid > 0) push('delivery_note_payments', {
      id: `dnp-${pad(dnN, 3)}`, delivery_note_id: dnId, date: iso(at(daysAgo, 11)), amount: paid, mode: 'VIREMENT',
      receipt_number: payments[0]?.bordereau_number, receipt_photo_url: null, created_at: iso(date),
    });
    tankLevel[tankId] += liters;
  };

  let carbCash = 0;
  const shifts: { name: 'Matin' | 'Soir'; start: number; end: number }[] = [
    { name: 'Matin', start: 6, end: 14 },
    { name: 'Soir', start: 14, end: 22 },
  ];
  const litersFor = (type: string) =>
    type === 'GASOIL' ? rf(260, 820) : type === 'ESSENCE' ? rf(160, 520) : type === 'SUPER' ? rf(35, 150) : rf(25, 110);

  for (let d = DAYS; d >= 0; d--) {
    // Deliveries scheduled the previous day arrive in the morning.
    for (let i = pendingDeliveries.length - 1; i >= 0; i--) {
      if (pendingDeliveries[i].day !== d) continue;
      doDelivery(d, pendingDeliveries[i].tankId);
      pendingDeliveries.splice(i, 1);
    }

    for (let s = 0; s < shifts.length; s++) {
      const sh = shifts[s];
      const start = at(d, sh.start, ri(0, 10));
      const end = at(d, sh.end, ri(0, 15));
      const isOpen = d === 0 && (s === 1 || NOW.getHours() < 14);
      if (d === 0 && s === 1 && NOW.getHours() < 14) break; // evening shift not started yet
      if (end.getTime() > NOW.getTime() && !isOpen) continue;

      const chefIdx = (d + s) % 3;
      const chef = chefs[chefIdx];
      const team = pompistes.filter((_, i) => i % 3 === chefIdx);
      const crew = sample(team, 3);
      const id = `bri-${pad(++bN, 3)}`;
      const pumpGroups = [['pump-01', 'pump-02'], ['pump-03', 'pump-04'], ['pump-05', 'pump-06']];
      const pompistePumpAssignments = crew.map((p, i) => ({ pompisteId: p.id, pumpIds: pumpGroups[i] }));
      const pompisteOfPump = (pumpId: string) => pompistePumpAssignments.find(a => a.pumpIds.includes(pumpId))!.pompisteId;

      const startIdx: Record<string, number> = {};
      const endIdx: Record<string, number> = {};
      const startTank: Record<string, any> = {};
      const endTank: Record<string, any> = {};
      tanks.forEach(t => { startTank[t.id] = { degrees: degreesOf(t.id, tankLevel[t.id]), liters: Math.round(tankLevel[t.id]) }; });

      const nozzleSummary: any[] = [];
      const perPompiste: Record<string, { liters: number; theoretical: number }> = {};
      nozzles.forEach(n => {
        startIdx[n.id] = r2(nozzleIdx[n.id]);
        if (isOpen) return;
        const liters = r2(litersFor(n.type) * (sh.name === 'Soir' ? 0.85 : 1));
        const end2 = r2(nozzleIdx[n.id] + liters);
        endIdx[n.id] = end2;
        nozzleIdx[n.id] = end2;
        tankLevel[n.tankId] = Math.max(0, tankLevel[n.tankId] - liters);
        const price = fuelPrices[n.type as keyof typeof fuelPrices];
        const revenue = r2(liters * price);
        const pump = pumpDefs.find(p => p.id === n.pumpId)!;
        nozzleSummary.push({
          nozzleId: n.id, startIdx: startIdx[n.id], endIdx: end2, liters, revenue,
          fuelType: n.type, price, pumpId: n.pumpId, pumpName: pump.name,
        });
        const pid = pompisteOfPump(n.pumpId);
        perPompiste[pid] ||= { liters: 0, theoretical: 0 };
        perPompiste[pid].liters += liters;
        perPompiste[pid].theoretical += revenue;
      });

      const brigadeRow = push('brigades', {
        id, date: ymd(start), shift: sh.name, chef_id: chef.id,
        status: isOpen ? 'Ouverte' : 'Clôturée',
        start_timestamp: iso(start), end_timestamp: isOpen ? null : iso(end),
        start_time: hhmm(start), end_time: isOpen ? null : hhmm(end),
        start_datetime: iso(start), end_datetime: isOpen ? null : iso(end),
        is_active: isOpen, notes: null, printed_at: null,
        start_indices: {}, end_indices: {},
        start_tank_levels: startTank, end_tank_levels: {},
        pompiste_data: {},
        pompiste_assignments: crew.map((p, i) => ({ pompisteId: p.id, trackId: `trk-0${i + 1}`, present: true })),
        start_nozzle_indices: startIdx, end_nozzle_indices: isOpen ? {} : endIdx,
        active_nozzle_ids: nozzles.map(n => n.id),
        can_reactivate: false, pompiste_pump_assignments: pompistePumpAssignments, versements: [],
        created_at: iso(start),
      });
      crew.forEach(p => push('brigade_pompiste_assignments', { brigade_id: id, pompiste_id: p.id }));
      if (isOpen) continue;

      tanks.forEach(t => {
        endTank[t.id] = { degrees: degreesOf(t.id, tankLevel[t.id]), liters: Math.round(tankLevel[t.id]), measured: true };
      });
      brigadeRow.end_tank_levels = endTank;

      const totalDue = r2(nozzleSummary.reduce((s2, n) => s2 + n.revenue, 0));
      const accId = `acc-${pad(bN, 3)}`;
      const justifs: any[] = [];
      // Client bons.
      const nBons = ri(1, 4);
      for (let k = 0; k < nBons; k++) {
        const client = pick(creditClients);
        const fuelType = chance(0.8) ? 'GASOIL' : 'ESSENCE';
        const liters = r2(rf(30, 380));
        const price = fuelPrices[fuelType as keyof typeof fuelPrices];
        const amount = r2(liters * price);
        clientConsumption[client.id] = (clientConsumption[client.id] || 0) + amount;
        justifs.push({
          id: `jst-${pad(++jN, 4)}`, accounting_id: accId, client_id: client.id, amount,
          client_type: client.type, payment_mode: client.payment_mode, justification_type: 'CLIENT',
          bank_account_id: null, notes: `Bon n° ${ri(1000, 9999)}`, client_name: client.name,
          fuel_type: fuelType, liters, price_per_liter: price, track_id: null,
          pompiste_id: pick(crew).id, expense_category: null,
        });
      }
      // Card payments (TPE / TAG).
      const nCards = ri(1, 3);
      for (let k = 0; k < nCards; k++) {
        const mode = chance(0.7) ? 'TPE' : 'TAG';
        const fuelType = pick(['GASOIL', 'ESSENCE', 'SUPER']);
        const price = fuelPrices[fuelType as keyof typeof fuelPrices];
        const liters = r2(rf(20, 250));
        const amount = r2(liters * price);
        const pomp = pick(crew);
        const jid = `jst-${pad(++jN, 4)}`;
        justifs.push({
          id: jid, accounting_id: accId, client_id: '', amount, client_type: null, payment_mode: null,
          justification_type: mode, bank_account_id: 'ba-02', notes: null,
          client_name: mode === 'TPE' ? pick(['Carte CIB', 'Carte Edahabia']) : 'TAG Naftal',
          fuel_type: fuelType, liters, price_per_liter: price, track_id: null, pompiste_id: pomp.id, expense_category: null,
        });
        push('tpe_transactions', {
          id: jid, brigade_id: id, accounting_id: accId, date: ymd(start), mode, client_name: justifs[justifs.length - 1].client_name,
          client_id: null, fuel_type: fuelType, liters, price_per_liter: price, amount, track_id: null, track_name: null,
          pompiste_id: pomp.id, pompiste_name: pomp.name, notes: null, created_at: iso(end),
        });
        ++tpeN;
        tx({
          id: txId(), date: iso(end), kind: 'TPE', amount,
          description: `${mode} brigade du ${ymd(start)} — ${pomp.name}`, account_to: 'ba-02', part: 'carburant',
          ref_type: 'brigade', ref_id: id,
        });
      }
      // A small expense paid from the brigade cash now and then.
      if (chance(0.12)) {
        const amount = pick([600, 900, 1200, 1500, 2500]);
        const jid = `jst-${pad(++jN, 4)}`;
        const label = pick(['Eau & café équipe', 'Produits de nettoyage', 'Ampoule piste', 'Petite réparation pistolet']);
        justifs.push({
          id: jid, accounting_id: accId, client_id: '', amount, client_type: null, payment_mode: null,
          justification_type: 'EXPENSE', bank_account_id: null, notes: null, client_name: label,
          fuel_type: null, liters: 0, price_per_liter: 0, track_id: null, pompiste_id: crew[0].id, expense_category: 'Divers',
        });
        brigadeExpenses.push({
          id: `exp-b${pad(++expN, 3)}`, date: iso(end), category: 'Divers', amount,
          description: `${label} — brigade ${sh.name} du ${ymd(start)}`, payment_mode: 'Espèces', cheque_number: null,
          bordereau_number: null, account_id: CAISSE_PART.carburant, part: 'carburant', paid_by: crew[0].name,
          recipient: null, status: 'Payé', receipt_url: null, created_by: chef.name, brigade_id: id,
          brigade_justification_id: jid, pompiste_id: crew[0].id, created_at: iso(end),
        });
      }
      justifs.forEach(j => push('brigade_accounting_justifications', j));

      const justTotal = justifs.reduce((s2, j) => s2 + j.amount, 0);
      const rest = chance(0.7) ? 0 : pick([-400, -250, 150, 300, 500, 850, 1200]);
      const cashReceived = r2(totalDue - justTotal - rest);
      const restPompiste = pick(crew).id;

      const pompisteSummary: Record<string, any> = {};
      crew.forEach(p => {
        const own = perPompiste[p.id] || { liters: 0, theoretical: 0 };
        const justifTotal = r2(justifs.filter(j => j.pompiste_id === p.id).reduce((s2, j) => s2 + j.amount, 0));
        const ecart = p.id === restPompiste ? rest : 0;
        pompisteSummary[p.id] = {
          litersSold: r2(own.liters), theoretical: r2(own.theoretical), justifTotal,
          cashReceived: r2(own.theoretical - justifTotal - ecart), ecart,
        };
      });
      brigadeRow.pompiste_data = Object.fromEntries(Object.entries(pompisteSummary).map(([pid, v]: [string, any]) => [pid, {
        litersSold: v.litersSold, theoretical: v.theoretical,
        collected: { cash: v.cashReceived, bons: v.justifTotal, cheques: 0 },
        totalCollected: v.cashReceived + v.justifTotal, decalage: v.ecart,
        pricePerLiter: 0,
      }]));

      const tankSummary = tanks.map(t => ({
        tankId: t.id, startL: startTank[t.id].liters, endL: endTank[t.id].liters,
        diff: startTank[t.id].liters - endTank[t.id].liters, ecart: 0, ecartMoney: 0,
      }));
      push('brigade_accounting', {
        id: accId, brigade_id: id, total_due: totalDue, cash_received: cashReceived, rest,
        tank_summary: tankSummary, nozzle_summary: nozzleSummary,
        decalage_summary: rest ? { [restPompiste]: { liters: 0, money: rest } } : {},
        pompiste_summary: pompisteSummary, cuve_verifications: {}, nozzle_verifications: {},
        rest_assigned_worker_type: rest ? 'pompiste' : null, rest_assigned_worker_id: rest ? restPompiste : null,
        rest_assigned_amount: Math.abs(rest), status: 'completed', created_by: chef.name, created_at: iso(end),
      });
      if (rest) {
        push('pompiste_decalage_history', {
          id: `dec-${pad(++decN, 4)}`, pompiste_id: restPompiste, brigade_id: id, date: ymd(start),
          amount: Math.abs(rest), type: rest < 0 ? 'BONUS' : 'RETENUE', created_at: iso(end),
        });
        if (Math.abs(rest) >= 500) {
          const p = pompistes.find(x => x.id === restPompiste)!;
          push('brigade_decalage_alerts', {
            id: `alr-${pad(decN, 4)}`, brigade_id: id, brigade_date: ymd(start),
            start_datetime: iso(start), end_datetime: iso(end), chef_id: chef.id, chef_name: chef.name,
            alert_type: rest > 0 ? 'VENTE_DIRECTE' : 'RETOUR_CUVE', tank_id: null, tank_name: null,
            pompiste_id: p.id, pompiste_name: p.name, decalage_liters: r2(Math.abs(rest) / fuelPrices.GASOIL),
            decalage_amount: Math.abs(rest), workers_info: [{ id: p.id, name: p.name, role: 'pompiste' }],
            is_dismissed: d > 7, created_at: iso(end),
          });
        }
      }
      carbCash += cashReceived;
      tx({
        id: txId(), date: iso(end), kind: 'BRIGADE', amount: cashReceived,
        description: `Encaissement brigade du ${ymd(start)}`, account_to: CAISSE, part: 'carburant',
        ref_type: 'brigade', ref_id: id, created_by: chef.name,
      });
    }

    // Every third evening the brigade takings go to the bank.
    if (d > 0 && d % 3 === 0 && carbCash > 0) {
      const amount = Math.floor((carbCash * 0.62) / 10000) * 10000;
      tx({ id: txId(), date: iso(at(d, 22, 30)), kind: 'TRANSFER', amount,
        description: 'Versement espèces carburant à la banque', account_from: CAISSE_PART.carburant, account_to: 'ba-01',
        part: 'carburant', bordereau_number: `VRS-${ri(100000, 999999)}` });
      carbCash -= amount;
    }

    // Tanks running low are reordered for the next morning.
    tanks.forEach(t => {
      if (tankLevel[t.id] < t.capacity * 0.4 && !pendingDeliveries.some(p => p.tankId === t.id)) {
        pendingDeliveries.push({ tankId: t.id, day: Math.max(0, d - 1) });
      }
    });
  }

  // Final pistolet / pump / tank state.
  nozzles.forEach((n, i) => push('pump_nozzles', {
    id: n.id, pump_id: n.pumpId, name: n.name, tank_id: n.tankId,
    last_index: r2(nozzleIdx[n.id]), start_index: r2(n.start), status: 'Actif',
    created_at: iso(new Date(at(390).getTime() + i * 60_000)),
  }));
  pumpDefs.forEach((p, i) => {
    const own = nozzles.filter(n => n.pumpId === p.id);
    const tank = tanks.find(t => t.id === own[0].tankId)!;
    push('pumps', {
      id: p.id, number: p.number, name: p.name, tank_id: tank.id, track_id: `trk-0${(i % 3) + 1}`,
      type: tank.type, last_index: r2(own.reduce((s2, n) => s2 + nozzleIdx[n.id], 0)),
      status: i === 5 && chance(0.3) ? 'Maintenance' : 'Actif', current_brigade_start_index: null,
      created_at: iso(new Date(at(390).getTime() + i * 60_000)),
    });
  });
  tanks.forEach((t, i) => push('tanks', {
    id: t.id, name: t.name, type: t.type, capacity: t.capacity, current: Math.round(tankLevel[t.id]),
    degrees: degreesOf(t.id, tankLevel[t.id]), alert_threshold: Math.round(t.capacity * 0.2),
    notes: null, is_favorite: i < 2, created_at: iso(new Date(at(395).getTime() + i * 60_000)),
  }));

  // Fuel invoices & receipts grouping the delivery notes.
  const dns = T.delivery_notes || [];
  for (let i = 0; i + 1 < dns.length; i += 2) {
    const group = [dns[i], dns[i + 1]];
    const total = r2(group.reduce((s2, g) => s2 + g.total, 0));
    const invId = `finv-${pad(i / 2 + 1, 3)}`;
    const date = new Date(group[1].date);
    const paid = i + 3 < dns.length ? total : r2(total * 0.5);
    push('fuel_invoices', {
      id: invId, invoice_number: `FN-${date.getFullYear()}-${pad(i / 2 + 101, 4)}`, invoice_date: ymd(date),
      creation_date: iso(date), reception_date: ymd(date), tva_active: true, tva_rate: 19,
      subtotal: r2(total / 1.19), tva_amount: r2(total - total / 1.19), total, amount_paid: paid, rest: r2(total - paid),
      status: paid >= total ? 'Payée' : 'Partielle', appointment_date: null, appointment_amount: null,
      appointment_notes: null, invoice_image_url: null, notes: null, created_at: iso(date),
    });
    group.forEach(g => push('fuel_invoice_bls', { invoice_id: invId, delivery_note_id: g.id }));
    if (paid > 0) {
      const rId = `frec-${pad(i / 2 + 1, 3)}`;
      push('fuel_receipts', {
        id: rId, receipt_number: `QT-${pad(i / 2 + 501, 5)}`, receipt_date: ymd(date), creation_date: iso(date),
        total_invoiced: total, amount_paid: paid, rest: r2(total - paid), is_debt_payment: false,
        receipt_image_url: null, notes: null, created_at: iso(date),
      });
      push('fuel_receipt_invoices', { receipt_id: rId, invoice_id: invId });
    }
  }

  // Supplier balances = what is still owed on their purchases.
  suppliers.forEach(s => {
    const own = fuelPurchases.filter(p => p.supplier_id === s.id);
    s.balance = r2(own.reduce((s2, p) => s2 + p.rest, 0));
    s.total_purchases = r2(own.reduce((s2, p) => s2 + p.total, 0));
    own.filter(p => p.rest > 0).forEach((p, k) => push('supplier_appointments', {
      id: `sap-${s.id}-${k}`, supplier_id: s.id, purchase_id: p.id, date: p.appointment_date,
      amount: p.rest, notes: 'Échéance de paiement', is_paid: false, created_at: p.created_at,
    }));
  });
  push('supplier_debt_payments', {
    id: 'sdp-001', supplier_id: 'sup-03', purchase_id: null, delivery_note_id: null, date: iso(at(12, 10)),
    amount: 45000, total_due: 120000, rest: 75000, payment_mode: 'CHEQUE', cheque_number: `${ri(1000000, 9999999)}`,
    notes: 'Acompte sur commande lubrifiants', created_at: iso(at(12)),
  });

  // Client accounts: payments of the credit clients, recharges of the advance ones.
  clients.forEach(c => {
    const consumed = clientConsumption[c.id] || 0;
    if (c.payment_mode === 'CREDIT') {
      const toPay = consumed + c.opening_debt;
      let paid = 0;
      const n = ri(1, 3);
      for (let k = 0; k < n; k++) {
        const amount = Math.round((toPay * rf(0.15, 0.3)) / 1000) * 1000;
        if (amount <= 0) continue;
        paid += amount;
        clientTx(c.id, at(ri(2, DAYS - 3), ri(9, 16)), 'PAYMENT', amount, pick(['VIREMENT', 'CHEQUE', 'ESPECES']));
      }
      c.debt = r2(Math.max(0, consumed + c.opening_debt - paid));
      if (c.debt > 0) push('client_appointments', {
        id: `cap-${c.id}`, client_id: c.id, sale_id: null, date: ymd(at(-ri(2, 20))),
        amount: Math.round(c.debt / 2), notes: 'Promesse de règlement', is_paid: false,
      });
    } else if (c.payment_mode === 'ADVANCE') {
      const recharged = (T.client_transactions || []).filter(t => t.client_id === c.id).reduce((s2, t) => s2 + t.amount, 0);
      let adv = recharged - consumed;
      if (adv < 20000) {
        const amount = Math.round((consumed - recharged + 150000) / 10000) * 10000;
        clientTx(c.id, at(ri(3, 20), 10), 'RECHARGE', amount, pick(['VIREMENT', 'ESPECES']));
        adv += amount;
      }
      c.balance = r2(adv); c.advance_balance = r2(adv);
    }
  });

  // ─── Station shop products & sales ──────────────────────────────────────────
  const brands = ['Total', 'Naftal', 'Shell', 'Castrol', 'Bosch', 'Valeo'];
  brands.forEach((b, i) => push('product_brands', { id: `brd-0${i + 1}`, name: b, created_at: iso(at(300)) }));
  const shopProducts: [string, string, number, number, string][] = [
    ['Huile moteur Total Quartz 5W40 — 4L', 'Lubrifiants', 3100, 3900, 'brd-01'],
    ['Huile moteur Naftal Chellia 15W40 — 5L', 'Lubrifiants', 2200, 2800, 'brd-02'],
    ['Huile Shell Helix HX7 10W40 — 4L', 'Lubrifiants', 3300, 4200, 'brd-03'],
    ['Castrol GTX 20W50 — 4L', 'Lubrifiants', 2900, 3600, 'brd-04'],
    ['Liquide de frein DOT4 — 500ml', 'Entretien auto', 420, 650, 'brd-02'],
    ['Liquide de refroidissement — 5L', 'Entretien auto', 900, 1300, 'brd-02'],
    ['Lave-glace été — 5L', 'Entretien auto', 280, 450, 'brd-02'],
    ['Balais essuie-glace Bosch 55cm', 'Accessoires', 850, 1400, 'brd-05'],
    ['Ampoule H4 Valeo', 'Accessoires', 380, 650, 'brd-06'],
    ['Désodorisant voiture', 'Accessoires', 150, 300, ''],
    ['Câbles de démarrage', 'Accessoires', 1300, 2200, ''],
    ['Triangle de signalisation', 'Accessoires', 700, 1200, ''],
    ['Eau minérale Lalla Khedidja 1.5L', 'Boissons', 35, 60, ''],
    ['Coca-Cola 1L', 'Boissons', 110, 170, ''],
    ['Hamoud Boualem Selecto 1L', 'Boissons', 90, 140, ''],
    ['Chips Mahboul 50g', 'Snacks', 40, 70, ''],
    ['Biscuits Bimo Galette', 'Snacks', 55, 90, ''],
    ['Lingettes nettoyantes', 'Hygiène', 180, 320, ''],
    ['Bouteille GPL 13kg (échange)', 'Accessoires', 180, 225, 'brd-02'],
    ['Graisse multi-usage 1kg', 'Lubrifiants', 650, 950, 'brd-02'],
  ];
  const products = shopProducts.map(([name, category, buy, sell, brandId], i) => push('products', {
    id: `prd-${pad(i + 1, 3)}`, ref: `ART-${pad(i + 1, 4)}`, name, category, buy_price: buy, selling_price: sell,
    stock: i === 4 || i === 11 ? ri(1, 3) : ri(8, 80), min_stock: 5, barcode: `613${ri(1000000000, 9999999999)}`,
    image_url: null, unit: category === 'Lubrifiants' ? 'Bidon' : 'Pièce', brand: brands[Number(brandId.slice(-1)) - 1] || null,
    brand_id: brandId || null, last_selling_price: sell, tva_rate: 19, sell_by_details: false, detail_capacity: null,
    detail_unit: null, created_at: iso(at(250 - i)),
  }));
  let ssN = 0;
  for (let d = 30; d >= 0; d--) {
    const n = ri(1, 4);
    for (let k = 0; k < n; k++) {
      const date = at(d, ri(8, 20), ri(0, 59));
      if (date.getTime() > NOW.getTime()) continue;
      const lines = sample(products, ri(1, 3)).map(p => ({ product: p, qty: ri(1, 3) }));
      const subtotal = lines.reduce((s2, l) => s2 + l.qty * l.product.selling_price, 0);
      const credit = chance(0.1);
      const client = credit ? pick(clients.filter(c => c.payment_mode === 'CREDIT')) : null;
      const id = `ssl-${pad(++ssN, 4)}`;
      push('shop_sales', {
        id, date: iso(date), client_id: client?.id ?? null, seller_id: pick(magasins).id, subtotal,
        tva_amount: 0, total: subtotal, payment_mode: credit ? 'CREDIT' : 'ESPECES', cheque_number: null,
        bon_number: null, bon_photo_url: null, amount_paid: credit ? 0 : subtotal, rest: credit ? subtotal : 0,
        status: credit ? 'Dette' : 'Payé', notes: null, printed_at: null, invoice_image_url: null, created_at: iso(date),
      });
      lines.forEach((l, li) => push('shop_sale_items', {
        id: `ssi-${pad(ssN, 4)}-${li}`, sale_id: id, product_id: l.product.id, product_name: l.product.name,
        quantity: l.qty, price: l.product.selling_price, tva: 0,
      }));
    }
  }

  // ─── Station expenses (every part) ──────────────────────────────────────────
  const expenseTemplates: [string, string, number, number, string][] = [
    ['Électricité', 'Facture Sonelgaz', 38000, 72000, 'carburant'],
    ['Eau', 'Facture SEAAL', 6000, 14000, 'carburant'],
    ['Entretien', 'Maintenance pompes et pistolets', 15000, 45000, 'carburant'],
    ['Entretien', 'Nettoyage séparateur hydrocarbures', 18000, 30000, 'carburant'],
    ['Téléphone & Internet', 'Abonnement Algérie Télécom', 4500, 6500, 'systeme'],
    ['Fournitures', 'Papeterie et rouleaux TPE', 2500, 6000, 'systeme'],
    ['Impôts', 'Acompte IBS / G50', 60000, 140000, 'systeme'],
    ['Transport', 'Carburant véhicule de service', 5000, 9000, 'carburant'],
    ['Entretien', 'Réparation climatisation salle', 12000, 25000, 'restaurant'],
    ['Électricité', 'Quote-part électricité cuisine', 15000, 28000, 'restaurant'],
    ['Fournitures', 'Vaisselle et ustensiles', 8000, 22000, 'restaurant'],
    ['Entretien', 'Maintenance machine à café', 7000, 16000, 'cafeteria'],
    ['Électricité', 'Quote-part électricité cafétéria', 8000, 15000, 'cafeteria'],
    ['Eau', 'Quote-part eau station de lavage', 9000, 18000, 'lavage'],
    ['Entretien', 'Révision nettoyeur haute pression', 11000, 24000, 'lavage'],
    ['Loyer', 'Location terrain annexe', 50000, 50000, 'systeme'],
    ['Divers', 'Frais bancaires', 1200, 3500, 'systeme'],
  ];
  let eN = 0;
  for (let k = 0; k < 48; k++) {
    const [category, description, min, max, part] = pick(expenseTemplates);
    const date = at(ri(0, DAYS), ri(8, 17), ri(0, 59));
    if (date.getTime() > NOW.getTime()) continue;
    const amount = Math.round(rf(min, max) / 100) * 100;
    const bank = part === 'systeme' || chance(0.35);
    const accountId = bank ? (chance(0.85) ? 'ba-01' : 'ba-04') : (CAISSE_PART[part] || CAISSE);
    const id = `exp-${pad(++eN, 3)}`;
    push('expenses', {
      id, date: iso(date), category, amount, description, payment_mode: bank ? 'Virement' : 'Espèces',
      cheque_number: null, bordereau_number: bank ? `BRD-${ri(10000, 99999)}` : null, account_id: accountId, part,
      paid_by: ADMIN_NAME, recipient: null, status: 'Payé', receipt_url: null, created_by: ADMIN_NAME,
      brigade_id: null, brigade_justification_id: null, pompiste_id: null, created_at: iso(date),
    });
    tx({
      id: txId(), date: iso(date), kind: 'EXPENSE', amount, description: `Dépense ${category} — ${description}`,
      account_from: accountId, part, ref_type: 'expense', ref_id: id,
    });
  }
  brigadeExpenses.forEach(e => push('expenses', e));

  // ─── Manual treasury movements ──────────────────────────────────────────────
  tx({ id: txId(), date: iso(at(DAYS, 9)), kind: 'DEPOSIT', amount: 400000, description: 'Fonds de caisse initial', account_to: CAISSE, part: 'systeme' });
  tx({ id: txId(), date: iso(at(20, 10)), kind: 'TRANSFER', amount: 300000, description: 'Placement vers compte épargne', account_from: 'ba-01', account_to: 'ba-03', part: 'systeme' });
  tx({ id: txId(), date: iso(at(9, 15)), kind: 'WITHDRAW', amount: 25000, description: 'Retrait pour menues dépenses', account_from: CAISSE, part: 'systeme' });
  tx({ id: txId(), date: iso(at(4, 11)), kind: 'TRANSFER', amount: 50000, description: 'Alimentation caisse lavage (monnaie)', account_from: 'ba-01', account_to: CAISSE_PART.lavage, part: 'lavage' });

  // ─── Inventories, daily reports, activity ───────────────────────────────────
  push('inventories', {
    id: 'inv-001', name: 'Inventaire cuves fin de mois', description: 'Jaugeage de contrôle', date: iso(at(15, 21)),
    user_name: ADMIN_NAME, type: 'Carburant', status: 'Validé',
    fuel_gaps: tanks.map(t => {
      const sys = Math.round(tankLevel[t.id] + rf(2000, 6000));
      const gap = ri(-60, 25);
      return { tankId: t.id, systemQty: sys, actualQty: sys + gap, degrees: degreesOf(t.id, sys + gap), gap, value: r2(gap * fuelBuyPrices[t.type as keyof typeof fuelBuyPrices]) };
    }),
    pump_index_gaps: [], product_gaps: [], adjustment_reason: 'Évaporation et arrondis de jauge', adjusted_at: iso(at(15, 22)),
    created_at: iso(at(15, 21)),
  });
  push('inventories', {
    id: 'inv-002', name: 'Inventaire boutique', description: 'Comptage des lubrifiants', date: iso(at(3, 20)),
    user_name: 'Nadia Belkacem', type: 'Magasin', status: 'En cours', fuel_gaps: [], pump_index_gaps: [],
    product_gaps: products.slice(0, 6).map(p => {
      const gap = ri(-2, 1);
      return { productId: p.id, systemQty: p.stock, actualQty: p.stock + gap, gap, value: gap * p.buy_price };
    }),
    adjustment_reason: null, adjusted_at: null, created_at: iso(at(3, 20)),
  });
  for (let d = 7; d >= 1; d--) {
    const day = ymd(at(d));
    const accs = (T.brigade_accounting || []).filter(a => (T.brigades || []).find(b => b.id === a.brigade_id)?.date === day);
    push('daily_reports', {
      id: `drp-${pad(8 - d, 3)}`, date: day, fuel_revenue: r2(accs.reduce((s2, a) => s2 + a.total_due, 0)),
      shop_revenue: r2((T.shop_sales || []).filter(s2 => s2.date.startsWith(day)).reduce((s2, x) => s2 + x.total, 0)),
      total_expenses: r2((T.expenses || []).filter(e => ymd(new Date(e.date)) === day).reduce((s2, e) => s2 + e.amount, 0)),
      cash_to_deposit: r2(accs.reduce((s2, a) => s2 + a.cash_received, 0)),
      tank_variations: [], brigade_ids: (T.brigades || []).filter(b => b.date === day).map(b => b.id),
      created_at: iso(at(d, 23)),
    });
  }
  ['Connexion', 'Création brigade', 'Clôture brigade', 'Ajout dépense', 'Règlement client', 'Achat carburant', 'Modification prix carburant']
    .forEach((action, i) => push('activity_log', {
      id: `log-${pad(i + 1, 3)}`, timestamp: iso(at(i, 9 + i)), user_name: ADMIN_NAME, action,
      details: `${action} (démo)`, module: 'Carburant', created_at: iso(at(i, 9 + i)),
    }));

  // ─── Business parts: Restaurant, Cafétéria, Lavage & Vidange ────────────────
  const bizState: Record<string, any> = {};
  (['restaurant', 'cafeteria', 'lavage'] as ModuleKey[]).forEach(key => {
    const { state, cashIn, cashOut } = buildModule(key, push);
    bizState[key] = state;
    // Weekly deposits of the part's takings, leaving a working float in the drawer.
    const weeks = Math.floor((BIZ_DAYS - 3) / 7) + 1;
    // Station expenses charged to this part and paid from its drawer leave it too.
    const stationCash = (T.expenses || []).filter(e => e.account_id === CAISSE_PART[key]).reduce((s2, e) => s2 + e.amount, 0);
    const perWeek = Math.max(0, Math.floor(((cashIn - cashOut - stationCash) * 0.6) / weeks / 5000) * 5000);
    const net = cashIn - cashOut - stationCash;
    if (net < 30000) {
      tx({ id: txId(), date: iso(at(BIZ_DAYS, 8)), kind: 'TRANSFER', amount: Math.ceil((30000 - net) / 5000) * 5000,
        description: 'Alimentation du fonds de caisse', account_from: 'ba-01', account_to: CAISSE_PART[key], part: key });
    }
    if (perWeek > 0) for (let d = BIZ_DAYS - 3; d >= 1; d -= 7) {
      tx({ id: txId(), date: iso(at(d, 18, key === 'restaurant' ? 0 : key === 'cafeteria' ? 10 : 20)), kind: 'TRANSFER',
        amount: perWeek, description: `Versement recette ${key === 'restaurant' ? 'restaurant' : key === 'cafeteria' ? 'cafétéria' : 'lavage'} à la banque`,
        account_from: CAISSE_PART[key], account_to: 'ba-01', part: key, bordereau_number: `VRS-${ri(100000, 999999)}` });
    }
  });
  push('biz_store', { id: 'biz-v1', state: bizState, rev: 1, updated_at: iso(NOW), created_at: iso(at(300)) });

  // ─── Client feedbacks ───────────────────────────────────────────────────────
  const feedbacks: [string, string][] = [
    ['fuel', 'Service rapide à la pompe, pompiste très poli. Merci !'],
    ['fuel', 'Le TPE ne fonctionnait pas hier soir, obligé de payer en espèces.'],
    ['fuel', 'Station propre et bien éclairée la nuit.'],
    ['fuel', "Il faudrait un gonfleur de pneus en état de marche."],
    ['restaurant', 'Le couscous du vendredi est excellent, portions généreuses.'],
    ['restaurant', "Attente un peu longue à midi, mais le personnel est accueillant."],
    ['restaurant', 'Pouvez-vous ajouter des plats végétariens au menu ?'],
    ['restaurant', 'Chorba délicieuse, prix raisonnables. Je reviendrai.'],
    ['restaurant', 'La salle manque de climatisation l’après-midi.'],
    ['cafeteria', 'Meilleur café de la route, bravo au barista.'],
    ['cafeteria', 'Les croissants étaient un peu secs ce matin.'],
    ['cafeteria', 'Très bon accueil, service rapide.'],
    ['cafeteria', 'Ajoutez du thé vert s’il vous plaît.'],
    ['lavage', 'Lavage complet impeccable, voiture comme neuve.'],
    ['lavage', 'Vidange faite en 20 minutes, très professionnel.'],
    ['lavage', "L'intérieur n'était pas bien aspiré sous les sièges."],
    ['lavage', 'Bon rapport qualité/prix, je recommande.'],
    ['lavage', 'Merci pour le rappel SMS de la vidange !'],
  ];
  feedbacks.forEach(([part, message], i) => push('client_feedbacks', {
    id: `fbk-${pad(i + 1, 3)}`, part,
    full_name: chance(0.7) ? pick(['Ali B.', 'Samira K.', 'Hocine M.', 'Fatima Z.', 'Rédha T.', 'Leila A.', 'Mounir S.']) : null,
    phone: chance(0.5) ? phone() : null, email: null, message,
    status: i % 3 === 0 ? 'unread' : 'read', created_at: iso(at(ri(0, 25), ri(8, 21))),
    read_at: i % 3 === 0 ? null : iso(at(ri(0, 5))), read_by: i % 3 === 0 ? null : ADMIN_NAME,
  }));

  T.whatsapp_messages ||= [];
  T.biz_sessions ||= [];
  T.biz_products ||= [];
  T.module_workers ||= [];
  T.fuel_sales ||= [];
  T.delivery_note_photos ||= [];
  return T;
}

// ═══════════════════════════════════════════════════════════════════════════════
// Business part generator
// ═══════════════════════════════════════════════════════════════════════════════
type ProdDef = { name: string; cat: string; unit: string; buy: number; sell: number; raw?: boolean; marque?: string };
type FicheDef = { name: string; cat: string; price: number; ingredients: [string, number][]; out: number };

const RESTAURANT_PRODUCTS: ProdDef[] = [
  { name: 'Viande hachée de bœuf', cat: 'Viandes', unit: 'Kg', buy: 1900, sell: 0, raw: true },
  { name: 'Poulet entier', cat: 'Viandes', unit: 'Kg', buy: 420, sell: 0, raw: true },
  { name: 'Agneau (épaule)', cat: 'Viandes', unit: 'Kg', buy: 2400, sell: 0, raw: true },
  { name: 'Merguez', cat: 'Viandes', unit: 'Kg', buy: 1500, sell: 0, raw: true },
  { name: 'Semoule moyenne', cat: 'Épicerie', unit: 'Kg', buy: 110, sell: 0, raw: true },
  { name: 'Riz long grain', cat: 'Épicerie', unit: 'Kg', buy: 180, sell: 0, raw: true },
  { name: 'Frik (blé concassé)', cat: 'Épicerie', unit: 'Kg', buy: 320, sell: 0, raw: true },
  { name: 'Pâtes spaghetti', cat: 'Épicerie', unit: 'Kg', buy: 160, sell: 0, raw: true },
  { name: 'Pommes de terre', cat: 'Légumes', unit: 'Kg', buy: 70, sell: 0, raw: true },
  { name: 'Tomates', cat: 'Légumes', unit: 'Kg', buy: 90, sell: 0, raw: true },
  { name: 'Oignons', cat: 'Légumes', unit: 'Kg', buy: 60, sell: 0, raw: true },
  { name: 'Courgettes', cat: 'Légumes', unit: 'Kg', buy: 110, sell: 0, raw: true },
  { name: 'Pois chiches', cat: 'Épicerie', unit: 'Kg', buy: 260, sell: 0, raw: true },
  { name: 'Huile de table Elio', cat: 'Épicerie', unit: 'L', buy: 250, sell: 0, raw: true },
  { name: 'Fromage râpé', cat: 'Crèmerie', unit: 'Kg', buy: 1300, sell: 0, raw: true },
  { name: 'Pain (baguette)', cat: 'Boulangerie', unit: 'Pièce', buy: 15, sell: 0, raw: true },
  { name: 'Olives vertes', cat: 'Épicerie', unit: 'Kg', buy: 450, sell: 0, raw: true },
  { name: 'Coca-Cola 33cl', cat: 'Boissons', unit: 'Pièce', buy: 60, sell: 120 },
  { name: 'Hamoud Boualem 33cl', cat: 'Boissons', unit: 'Pièce', buy: 45, sell: 100 },
  { name: 'Eau minérale 50cl', cat: 'Boissons', unit: 'Pièce', buy: 20, sell: 50 },
  { name: 'Jus Rouiba orange 1L', cat: 'Boissons', unit: 'Pièce', buy: 130, sell: 250 },
  { name: 'Lben (petit-lait) 1L', cat: 'Boissons', unit: 'Pièce', buy: 70, sell: 130 },
  { name: 'Yaourt Soummam', cat: 'Desserts', unit: 'Pièce', buy: 25, sell: 60 },
];
const RESTAURANT_FICHES: FicheDef[] = [
  { name: 'Couscous au poulet', cat: 'Plats', price: 650, out: 20, ingredients: [['Semoule moyenne', 3], ['Poulet entier', 5], ['Courgettes', 2], ['Pois chiches', 0.8], ['Oignons', 1]] },
  { name: 'Chorba frik', cat: 'Soupes', price: 250, out: 25, ingredients: [['Frik (blé concassé)', 1], ['Agneau (épaule)', 1.2], ['Tomates', 2], ['Pois chiches', 0.6], ['Oignons', 0.8]] },
  { name: 'Tajine zitoune', cat: 'Plats', price: 700, out: 15, ingredients: [['Poulet entier', 4], ['Olives vertes', 1], ['Pommes de terre', 2], ['Oignons', 1]] },
  { name: 'Grillades mixtes', cat: 'Grillades', price: 1100, out: 12, ingredients: [['Agneau (épaule)', 2], ['Merguez', 1.5], ['Tomates', 1], ['Pain (baguette)', 12]] },
  { name: 'Burger maison', cat: 'Fast-food', price: 550, out: 20, ingredients: [['Viande hachée de bœuf', 2.4], ['Fromage râpé', 0.6], ['Tomates', 1], ['Pain (baguette)', 10]] },
  { name: 'Pâtes bolognaise', cat: 'Plats', price: 500, out: 18, ingredients: [['Pâtes spaghetti', 2], ['Viande hachée de bœuf', 1.5], ['Tomates', 2], ['Fromage râpé', 0.3]] },
  { name: 'Riz au poulet', cat: 'Plats', price: 550, out: 18, ingredients: [['Riz long grain', 2.5], ['Poulet entier', 4], ['Oignons', 0.6]] },
  { name: 'Frites portion', cat: 'Accompagnements', price: 200, out: 30, ingredients: [['Pommes de terre', 7], ['Huile de table Elio', 1.5]] },
  { name: 'Salade variée', cat: 'Entrées', price: 250, out: 20, ingredients: [['Tomates', 2], ['Oignons', 0.5], ['Olives vertes', 0.4]] },
  { name: 'Sandwich merguez', cat: 'Fast-food', price: 350, out: 25, ingredients: [['Merguez', 2], ['Pain (baguette)', 25], ['Pommes de terre', 2]] },
];
const CAFETERIA_PRODUCTS: ProdDef[] = [
  { name: 'Café en grains arabica', cat: 'Matières premières', unit: 'Kg', buy: 2600, sell: 0, raw: true },
  { name: 'Lait entier UHT', cat: 'Matières premières', unit: 'L', buy: 110, sell: 0, raw: true },
  { name: 'Sucre en poudre', cat: 'Matières premières', unit: 'Kg', buy: 95, sell: 0, raw: true },
  { name: 'Thé vert Tiziri', cat: 'Matières premières', unit: 'Kg', buy: 1400, sell: 0, raw: true },
  { name: 'Menthe fraîche', cat: 'Matières premières', unit: 'Kg', buy: 400, sell: 0, raw: true },
  { name: 'Farine T55', cat: 'Matières premières', unit: 'Kg', buy: 75, sell: 0, raw: true },
  { name: 'Beurre', cat: 'Matières premières', unit: 'Kg', buy: 1500, sell: 0, raw: true },
  { name: 'Chocolat noir', cat: 'Matières premières', unit: 'Kg', buy: 1800, sell: 0, raw: true },
  { name: 'Œufs', cat: 'Matières premières', unit: 'Pièce', buy: 18, sell: 0, raw: true },
  { name: 'Eau minérale 50cl', cat: 'Boissons fraîches', unit: 'Pièce', buy: 20, sell: 40 },
  { name: 'Coca-Cola 33cl', cat: 'Boissons fraîches', unit: 'Pièce', buy: 60, sell: 100 },
  { name: 'Ifri Citron 33cl', cat: 'Boissons fraîches', unit: 'Pièce', buy: 45, sell: 80 },
  { name: 'Jus Rouiba cocktail 25cl', cat: 'Boissons fraîches', unit: 'Pièce', buy: 45, sell: 80 },
  { name: 'Red Bull 25cl', cat: 'Boissons fraîches', unit: 'Pièce', buy: 190, sell: 300 },
  { name: 'Chips Mahboul', cat: 'Snacks', unit: 'Pièce', buy: 40, sell: 70 },
  { name: 'Barre Twix', cat: 'Snacks', unit: 'Pièce', buy: 90, sell: 150 },
  { name: 'Gaufrettes Bimo', cat: 'Snacks', unit: 'Pièce', buy: 30, sell: 60 },
  { name: 'Chewing-gum', cat: 'Snacks', unit: 'Pièce', buy: 10, sell: 20 },
];
const CAFETERIA_FICHES: FicheDef[] = [
  { name: 'Café express', cat: 'Boissons chaudes', price: 60, out: 120, ingredients: [['Café en grains arabica', 0.9], ['Sucre en poudre', 0.6]] },
  { name: 'Café au lait', cat: 'Boissons chaudes', price: 80, out: 80, ingredients: [['Café en grains arabica', 0.6], ['Lait entier UHT', 8], ['Sucre en poudre', 0.4]] },
  { name: 'Cappuccino', cat: 'Boissons chaudes', price: 120, out: 50, ingredients: [['Café en grains arabica', 0.4], ['Lait entier UHT', 6], ['Chocolat noir', 0.1]] },
  { name: 'Thé à la menthe', cat: 'Boissons chaudes', price: 50, out: 80, ingredients: [['Thé vert Tiziri', 0.3], ['Menthe fraîche', 0.4], ['Sucre en poudre', 0.8]] },
  { name: 'Croissant au beurre', cat: 'Viennoiseries', price: 60, out: 40, ingredients: [['Farine T55', 2.5], ['Beurre', 1.2], ['Œufs', 6], ['Sucre en poudre', 0.3]] },
  { name: 'Pain au chocolat', cat: 'Viennoiseries', price: 70, out: 40, ingredients: [['Farine T55', 2.5], ['Beurre', 1.2], ['Chocolat noir', 0.5]] },
  { name: 'Msemen', cat: 'Viennoiseries', price: 50, out: 40, ingredients: [['Farine T55', 3], ['Beurre', 0.5]] },
  { name: 'Crêpe chocolat', cat: 'Desserts', price: 150, out: 25, ingredients: [['Farine T55', 1], ['Lait entier UHT', 2], ['Œufs', 10], ['Chocolat noir', 0.5]] },
];
const LAVAGE_PRODUCTS: ProdDef[] = [
  { name: 'Huile Total Quartz 5W30 — 5L', cat: 'Huiles moteur', unit: 'Bidon', buy: 4200, sell: 5400, marque: 'Total' },
  { name: 'Huile Total Quartz 10W40 — 5L', cat: 'Huiles moteur', unit: 'Bidon', buy: 3300, sell: 4300, marque: 'Total' },
  { name: 'Huile Naftal Chellia 15W40 — 5L', cat: 'Huiles moteur', unit: 'Bidon', buy: 2200, sell: 2900, marque: 'Naftal' },
  { name: 'Huile Shell Helix HX8 5W40 — 4L', cat: 'Huiles moteur', unit: 'Bidon', buy: 4400, sell: 5600, marque: 'Shell' },
  { name: 'Huile moteur en vrac', cat: 'Huiles moteur', unit: 'L', buy: 520, sell: 750, marque: 'Naftal' },
  { name: 'Filtre à huile Purflux', cat: 'Filtres', unit: 'Pièce', buy: 650, sell: 1100, marque: 'Purflux' },
  { name: 'Filtre à air Mann', cat: 'Filtres', unit: 'Pièce', buy: 900, sell: 1500, marque: 'Mann' },
  { name: 'Filtre habitacle Bosch', cat: 'Filtres', unit: 'Pièce', buy: 750, sell: 1300, marque: 'Bosch' },
  { name: 'Filtre à gasoil Bosch', cat: 'Filtres', unit: 'Pièce', buy: 1100, sell: 1800, marque: 'Bosch' },
  { name: 'Liquide de refroidissement 5L', cat: 'Liquides', unit: 'Bidon', buy: 900, sell: 1400, marque: 'Naftal' },
  { name: 'Shampoing carrosserie 20L', cat: 'Produits lavage', unit: 'Bidon', buy: 3800, sell: 0, raw: true },
  { name: 'Cire lustrante 5L', cat: 'Produits lavage', unit: 'Bidon', buy: 2600, sell: 0, raw: true },
  { name: 'Nettoyant jantes 5L', cat: 'Produits lavage', unit: 'Bidon', buy: 1900, sell: 0, raw: true },
  { name: 'Rénovateur plastiques', cat: 'Produits lavage', unit: 'Pièce', buy: 650, sell: 1100 },
  { name: 'Désodorisant sapin', cat: 'Accessoires', unit: 'Pièce', buy: 120, sell: 250 },
  { name: 'Microfibre (lot de 3)', cat: 'Accessoires', unit: 'Pièce', buy: 300, sell: 550 },
];

const MODULE_PREFIX: Record<ModuleKey, string> = { restaurant: 'rs', cafeteria: 'cf', lavage: 'lv' };

const WORKERS: Record<ModuleKey, [string, string, 'jour' | 'mois' | 'pourcentage', number, string?][]> = {
  restaurant: [
    ['Sofiane Mansouri', 'Caissier / Chef de salle', 'mois', 48000],
    ['Djamila Hadj', 'Cuisinière', 'mois', 55000],
    ['Rafik Guendouz', 'Commis de cuisine', 'mois', 38000],
    ['Yasmine Oukil', 'Serveuse', 'jour', 1600],
    ['Mounir Belaid', 'Serveur', 'jour', 1600],
    ['Lotfi Zenati', 'Plongeur', 'jour', 1300],
  ],
  cafeteria: [
    ['Imane Cherif', 'Caissière', 'mois', 36000],
    ['Réda Hamadi', 'Barista', 'mois', 38000],
    ['Aicha Mebarki', 'Pâtissière', 'jour', 1200],
  ],
  lavage: [
    ['Bilal Kaci', 'Caissier / Réception', 'mois', 45000],
    ['Hamza Brahimi', 'Laveur', 'pourcentage', 30, 'lavage'],
    ['Adel Boukhalfa', 'Laveur', 'pourcentage', 30, 'lavage'],
    ['Mohamed Kheddache', 'Mécanicien vidange', 'pourcentage', 35, 'reparation'],
    ['Zakaria Aouadi', 'Polyvalent', 'pourcentage', 30, 'both'],
  ],
};

const CAR_MODELS: [string, string][] = [
  ['Renault', 'Symbol'], ['Hyundai', 'Accent'], ['Peugeot', '208'], ['Volkswagen', 'Golf 7'], ['Dacia', 'Logan'],
  ['Kia', 'Picanto'], ['Toyota', 'Hilux'], ['Seat', 'Ibiza'], ['Chevrolet', 'Sail'], ['Fiat', 'Tipo'],
  ['Renault', 'Clio 4'], ['Hyundai', 'Tucson'], ['Nissan', 'Qashqai'], ['Suzuki', 'Swift'], ['Skoda', 'Octavia'],
];
const COLORS = ['Blanc', 'Gris', 'Noir', 'Bleu', 'Rouge', 'Argent'];

function buildModule(key: ModuleKey, push: (tbl: string, row: any) => any): any {
  const px = MODULE_PREFIX[key];
  const isService = key === 'lavage';
  const defs = key === 'restaurant' ? RESTAURANT_PRODUCTS : key === 'cafeteria' ? CAFETERIA_PRODUCTS : LAVAGE_PRODUCTS;
  const ficheDefs = key === 'restaurant' ? RESTAURANT_FICHES : key === 'cafeteria' ? CAFETERIA_FICHES : [];

  // Categories & marques.
  const catNames = [...new Set([...defs.map(d => d.cat), ...ficheDefs.map(f => f.cat)])];
  const categories = catNames.map((name, i) => ({ id: `${px}-ct-${pad(i + 1, 2)}`, name }));
  const catId = (name: string) => categories.find(c => c.name === name)!.id;
  const marqueNames = [...new Set(defs.map(d => d.marque).filter(Boolean) as string[])];
  const marques = marqueNames.map((name, i) => ({ id: `${px}-mq-${pad(i + 1, 2)}`, name }));
  const roleNames = [...new Set(WORKERS[key].map(w => w[1]))];
  const roles = roleNames.map((name, i) => ({ id: `${px}-rl-${pad(i + 1, 2)}`, name }));

  // Products (stored in `biz_products`).
  const products = defs.map((d, i) => {
    const principal = d.raw ? ri(40, 160) : ri(60, 240);
    const current = i % 7 === 3 ? ri(1, 4) : Math.round(principal * rf(0.25, 0.7));
    return {
      id: `${px}-pd-${pad(i + 1, 3)}`, name: d.name, description: '', barcode: `613${ri(1000000000, 9999999999)}`,
      marqueId: d.marque ? marques.find(m => m.name === d.marque)?.id : undefined, marqueName: d.marque,
      categoryId: catId(d.cat), categoryName: d.cat,
      principalQty: principal, currentQty: current, minQty: d.raw ? 10 : 12,
      purchasePrice: d.buy, averageCost: d.buy, lastPurchasePrice: d.buy, salePrice: d.sell, unit: d.unit,
      hasExpiration: key !== 'lavage' && !d.raw && chance(0.3),
      expirationDate: undefined as string | undefined,
      isRawMaterial: !!d.raw, createdAt: iso(at(200 - i)),
      ...(key === 'lavage' && d.cat === 'Filtres' ? {
        refs: [{ id: `${px}-ref-${i}`, ref: `${pick(['LS', 'W', 'C', 'F'])}${ri(100, 999)}`, brand: d.marque }],
        cars: [{ id: `${px}-car-${i}`, marque: 'Renault', name: 'Symbol', year: '2013-2020', gearbox: 'manuelle' }],
      } : {}),
    };
  });
  products.forEach(p => { if (p.hasExpiration) p.expirationDate = ymd(at(-ri(-5, 120))); });
  products.forEach(p => push('biz_products', { id: p.id, module_key: key, data: p, created_at: p.createdAt }));
  const byName = (name: string) => products.find(p => p.name === name)!;
  const sellable = products.filter(p => !p.isRawMaterial && p.salePrice > 0);

  // Suppliers & clients.
  const supplierNames = key === 'restaurant'
    ? ['Boucherie El Baraka', 'Marché de gros Eucalyptus', 'Sarl Agro-Distribution Mitidja', 'Boissons Rouiba Distribution', 'Laiterie Soummam — dépôt']
    : key === 'cafeteria'
      ? ['Café Facto Torréfaction', 'Laiterie Candia — dépôt', 'Sarl Snack Distribution', 'Boulangerie industrielle Amour']
      : ['Total Lubrifiants Algérie', 'Sarl Filtres & Pièces Auto', 'Karcher Algérie — produits', 'Naftal Lubrifiants'];
  const suppliers = supplierNames.map((name, i) => ({
    id: `${px}-sp-${pad(i + 1, 2)}`, name, phone: `0${ri(21, 29)} ${ri(10, 99)} ${ri(10, 99)} ${ri(10, 99)}`,
    address: pick(['Alger', 'Blida', 'Boumerdès', 'Rouiba', 'Oued Smar']), createdAt: iso(at(250 - i)),
  }));
  const clientNames = isService
    ? ['Rachid Ammari', 'Salima Belhocine', 'Farouk Djenadi', 'Kamel Bouzidi', 'Nour El Houda Saidi', 'Tarek Hamdi',
      'Sarl Location Auto El Amel', 'Walid Messaoudi', 'Lynda Aït Said', 'Hocine Bennour', 'Mehdi Laribi', 'Cosider — Parc auto',
      'Samia Ouchene', 'Yazid Rahmoune', 'Abdelkader Ferroukhi', 'Taxi Omar Benkhelifa', 'Ryad Guerfi', 'Nassima Hamza']
    : key === 'restaurant'
      ? ['Cosider — Chantier Rouiba', 'Sarl Logistique Atlas', 'Bureau d’études Tadjer', 'École de conduite El Nadjah', 'Hocine Merabet', 'Transport Benmansour', 'Clinique El Azhar', 'Karima Taleb']
      : ['Bureau Sonelgaz El Hamiz', 'Agence CNEP', 'Nadir Hachemi', 'Pharmacie Ibn Sina', 'Rym Boudjemaa', 'Garage Moderne'];
  const clients = clientNames.map((name, i) => {
    const c: any = {
      id: `${px}-cl-${pad(i + 1, 2)}`, name, phone: `0${pick(['5', '6', '7'])}${ri(10, 99)} ${ri(10, 99)} ${ri(10, 99)} ${ri(10, 99)}`,
      address: pick(['Dar El Beïda', 'Rouiba', 'Bab Ezzouar', 'El Hamiz', 'Reghaïa']), createdAt: iso(at(BIZ_DAYS + 20 + i)),
    };
    if (i % 4 === 1) { c.openingDebt = pick([6000, 12000, 18500]); c.openingDate = ymd(at(BIZ_DAYS + 5)); c.openingNotes = 'Reprise ancien carnet'; }
    if (isService) {
      const nCars = i % 5 === 0 ? 2 : 1;
      c.cars = Array.from({ length: nCars }, (_, k) => {
        const [marque, model] = pick(CAR_MODELS);
        return {
          id: `${px}-car-${pad(i + 1, 2)}-${k}`, marque, name: model, color: pick(COLORS), year: String(ri(2010, 2024)),
          immatriculation: `${ri(10000, 99999)} ${ri(110, 124)} ${pick(['16', '35', '09', '15'])}`,
          kilometrage: ri(40000, 230000), kilometrageAt: ymd(at(ri(1, 40))), createdAt: c.createdAt,
        };
      });
    }
    return c;
  });

  // Workers.
  const workers = WORKERS[key].map(([name, roleName, salaryType, salaryAmount, kind], i) => {
    const id = `${px}-wrk-${pad(i + 1, 2)}`;
    const account = DEMO_ACCOUNTS.find(a => a.workerId === id);
    const w: any = {
      id, authUserId: account?.userId, name, cin: `${ri(100000000, 999999999)}`, phone: `0${pick(['5', '6', '7'])}${ri(10, 99)} ${ri(10, 99)} ${ri(10, 99)} ${ri(10, 99)}`,
      roleName, workerKind: kind as any, paid: true, salaryType,
      salaryAmount: salaryType === 'pourcentage' ? 0 : salaryAmount,
      percentage: salaryType === 'pourcentage' ? salaryAmount : undefined,
      workDays: salaryType === 'jour' ? [0, 1, 2, 3, 4, 6] : undefined,
      cnasDate: ymd(at(ri(100, 500))),
      hasAccount: !!account, email: account?.email, username: account?.username,
      startDate: ymd(at(ri(90, 700))), permissions: {} as Record<string, boolean>,
      acomptes: [] as any[], absences: [] as any[], payments: [] as any[],
      inventoryLiable: i === 0, createdAt: iso(at(ri(90, 700))),
    };
    if (account) {
      interfacesForModule(key).forEach(it => ['voir', 'creer', 'modifier', 'supprimer'].forEach(a => { w.permissions[`${it.id}.${a}`] = true; }));
      push('module_workers', {
        id, module_key: key, name, role_name: roleName, phone: w.phone, email: account.email,
        username: account.username, auth_user_id: account.userId, has_account: true, permissions: w.permissions,
        created_at: w.createdAt,
      });
    }
    return w;
  });
  const cashier = workers[0];

  // Payroll: last month's salary + current acomptes.
  workers.forEach((w, i) => {
    const prev = new Date(NOW.getFullYear(), NOW.getMonth() - 1, 1);
    const period = monthKey(prev);
    if (w.salaryType !== 'pourcentage') {
      const acompte = chance(0.5) ? pick([2000, 3000, 5000]) : 0;
      if (acompte) w.acomptes.push({ id: `${w.id}-ac-1`, date: ymd(new Date(prev.getFullYear(), prev.getMonth(), ri(8, 20))), amount: acompte, description: 'Avance', paid: true });
      const base = w.salaryType === 'mois' ? w.salaryAmount : w.salaryAmount * 26;
      w.payments.push({
        id: `${w.id}-py-1`, period, amount: base - acompte, date: ymd(at(Math.min(NOW.getDate() - 1 + 0, 28) + 1, 10)),
        description: `Salaire ${period}`, mode: 'Espèces',
      });
    }
    if (chance(0.5)) w.acomptes.push({ id: `${w.id}-ac-2`, date: ymd(at(ri(1, Math.max(1, NOW.getDate() - 1)))), amount: pick([1500, 2000, 3000]), description: 'Acompte', paid: false });
    if (i % 3 === 2) w.absences.push({ id: `${w.id}-ab-1`, date: ymd(at(ri(2, 20))), cost: w.salaryType === 'jour' ? w.salaryAmount : 1500, description: 'Absence', paid: false });
  });

  // Fiches techniques (recipes), productions and comptoir.
  const fiches = ficheDefs.map((f, i) => {
    const ingredients = f.ingredients.map(([pname, qty]) => {
      const p = byName(pname);
      return { productId: p.id, productName: p.name, quantityUsed: qty, unitCost: p.purchasePrice, lineCost: r2(qty * p.purchasePrice), unit: p.unit, sourceType: 'stock' as const };
    });
    const totalCost = r2(ingredients.reduce((s, x) => s + x.lineCost, 0));
    const costPerUnit = r2(totalCost / f.out);
    return {
      id: `${px}-fc-${pad(i + 1, 2)}`, name: f.name, categoryId: catId(f.cat), categoryName: f.cat,
      description: `Recette standard — ${f.out} portions`, ingredients, sellByUnit: true, sellUnit: 'Portion',
      usableInProduction: true, productUnit: 'Portion', directSale: false,
      outputQuantity: f.out, unitPrice: f.price, totalCost, costPerUnit, totalValue: f.out * f.price,
      gainsPerUnit: r2(f.price - costPerUnit), totalGains: r2(f.out * f.price - totalCost), createdAt: iso(at(180 - i)),
    };
  });
  const productions: any[] = [];
  const destructions: any[] = [];
  const comptoir: any[] = [];
  for (let d = Math.min(21, BIZ_DAYS); d >= 0 && fiches.length; d -= 1) {
    fiches.filter((_, i) => (i + d) % 3 === 0 || i < 2).forEach(f => {
      const loss = chance(0.1) ? ri(1, 3) : 0;
      const output = f.outputQuantity - loss;
      productions.push({
        id: `${px}-pr-${pad(productions.length + 1, 4)}`, name: f.name, categoryName: f.categoryName, ficheId: f.id,
        date: iso(at(d, 7, ri(0, 40))), createdBy: workers[1]?.name, ingredients: f.ingredients,
        outputQuantity: output, expectedQuantity: f.outputQuantity, sentToComptoir: output, unit: 'Portion',
        unitPrice: f.unitPrice, totalCost: f.totalCost, totalValue: r2(output * f.unitPrice), costPerUnit: f.costPerUnit,
        hasLoss: loss > 0, lossQuantity: loss, lossValue: r2(loss * f.costPerUnit), lossReason: loss ? 'Cuisson ratée' : undefined,
      });
    });
  }
  fiches.forEach((f, i) => comptoir.push({
    id: `${px}-cp-${pad(i + 1, 2)}`, productName: f.name, categoryName: f.categoryName, qty: ri(0, 14), unit: 'Portion',
    unitPrice: f.unitPrice, purchasePrice: f.costPerUnit, date: iso(at(0, 7, 30)),
    sourceProductionId: productions.filter(p => p.ficheId === f.id).slice(-1)[0]?.id,
  }));

  // Sessions (one per day, today's still open) and sales.
  const sessions: any[] = [];
  const sales: any[] = [];
  const perDay = key === 'restaurant' ? [16, 28] : key === 'cafeteria' ? [20, 32] : [3, 6];
  const comptoirLines = comptoir;
  for (let d = BIZ_DAYS; d >= 0; d--) {
    const openAt = at(d, key === 'cafeteria' ? 6 : key === 'restaurant' ? 10 : 8, 30);
    if (openAt.getTime() > NOW.getTime()) continue;
    const sessionId = `${px}-ss-${pad(BIZ_DAYS - d + 1, 3)}`;
    const opening = key === 'lavage' ? 3000 : 5000;
    const closeAt = at(d, key === 'cafeteria' ? 19 : 22, 30);
    const isOpen = d === 0;
    let cash = 0; let credit = 0;
    const n = ri(perDay[0], perDay[1]);
    for (let k = 0; k < n; k++) {
      const h = (key === 'cafeteria' ? 7 : key === 'restaurant' ? 11 : 9) + rnd() * (key === 'cafeteria' ? 12 : 10);
      const date = at(d, Math.floor(h), ri(0, 59));
      if (date.getTime() > NOW.getTime()) continue;
      let items: any[];
      if (key === 'lavage') {
        items = sample(sellable, ri(1, 2)).map(p => ({ productId: p.id, productName: p.name, qty: 1, unitPrice: p.salePrice, unitCost: p.purchasePrice, total: p.salePrice }));
      } else {
        const dishes = sample(comptoirLines, ri(1, 3)).map(c => {
          const qty = ri(1, 3);
          return { productId: c.id, productName: c.productName, qty, unitPrice: c.unitPrice, unitCost: c.purchasePrice, total: qty * c.unitPrice };
        });
        const drinks = chance(0.55) ? sample(sellable, 1).map(p => {
          const qty = ri(1, 2);
          return { productId: p.id, productName: p.name, qty, unitPrice: p.salePrice, unitCost: p.purchasePrice, total: qty * p.salePrice };
        }) : [];
        items = [...dishes, ...drinks];
      }
      const subtotal = items.reduce((s, l) => s + l.total, 0);
      const discount = chance(0.06) ? Math.round(subtotal * 0.1) : 0;
      const total = subtotal - discount;
      const onCredit = chance(0.06);
      const client = onCredit || chance(0.15) ? pick(clients) : null;
      const paid = onCredit ? (chance(0.3) ? Math.round(total / 2) : 0) : total;
      const seller = pick(workers.slice(0, Math.max(1, key === 'lavage' ? 1 : 2)));
      const saleId = `${px}-sl-${pad(sales.length + 1, 5)}`;
      const sale: any = {
        id: saleId, ref: `${px.toUpperCase()}-${ymd(date).replace(/-/g, '').slice(2)}-${pad(k + 1, 3)}`,
        clientId: client?.id, clientName: client?.name || (key === 'restaurant' ? 'Client en salle' : 'Client de passage'),
        items, subtotal, reduction: discount, discountType: discount ? 'percent' : undefined, discountValue: discount ? 10 : undefined,
        total, paid, rest: total - paid, date: iso(date), status: onCredit ? 'crédit' : 'payée',
        createdBy: seller.name, sessionId, workerId: seller.id, workerName: seller.name,
      };
      // Some credit sales were settled later.
      if (onCredit && d > 5 && chance(0.5)) {
        const later = at(d - ri(1, Math.min(5, d)), 12);
        sale.payments = [
          ...(paid > 0 ? [{ id: `${saleId}-p1`, date: iso(date), amount: paid, mode: 'Espèces' }] : []),
          { id: `${saleId}-p2`, date: iso(later), amount: total - paid, mode: 'Espèces', notes: 'Règlement du crédit' },
        ];
        sale.paid = total; sale.rest = 0; sale.status = 'payée';
      }
      if (!onCredit && chance(0.01) && d > 2) {
        sale.status = 'retournée'; sale.refundedAmount = total; sale.refundedAt = iso(date); sale.returnReason = 'Erreur de commande';
      }
      sales.push(sale);
      if (sale.status === 'payée' || sale.status === 'crédit') { cash += paid; credit += total - paid; }
    }
    const decalage = isOpen ? undefined : pick([0, 0, 0, -100, 50, -200, 150]);
    sessions.push({
      id: sessionId, ref: `SES-${px.toUpperCase()}-${pad(BIZ_DAYS - d + 1, 3)}`, workerId: cashier.id, workerName: cashier.name,
      openingCash: opening, openedAt: iso(openAt), closedAt: isOpen ? undefined : iso(closeAt),
      closingCash: isOpen ? undefined : opening + cash + (decalage || 0), status: isOpen ? 'open' : 'closed',
      theoretical: isOpen ? undefined : opening + cash, credit: isOpen ? undefined : credit, decalage,
      authUserId: cashier.authUserId, openedById: cashier.id, openedByName: cashier.name,
      closedById: isOpen ? undefined : cashier.id, closedByName: isOpen ? undefined : cashier.name,
    });
  }
  sessions.forEach(s => push('biz_sessions', {
    id: s.id, module_key: key, ref: s.ref, worker_id: s.workerId, worker_name: s.workerName,
    opening_cash: s.openingCash, opened_at: s.openedAt, closed_at: s.closedAt ?? null,
    closing_cash: s.closingCash ?? null, status: s.status, notes: null, theoretical: s.theoretical ?? null,
    credit: s.credit ?? null, decalage: s.decalage ?? null, auth_user_id: s.authUserId ?? null,
    opened_by_id: s.openedById, opened_by_name: s.openedByName, closed_by_id: s.closedById ?? null,
    closed_by_name: s.closedByName ?? null, created_at: s.openedAt,
  }));

  // Lavage & vidange interventions.
  const reparations: any[] = [];
  const payRequests: any[] = [];
  if (isService) {
    const washers = workers.filter(w => w.workerKind === 'lavage' || w.workerKind === 'both');
    const mechanics = workers.filter(w => w.workerKind === 'reparation' || w.workerKind === 'both');
    const oils = products.filter(p => p.categoryName === 'Huiles moteur');
    const filters = products.filter(p => p.categoryName === 'Filtres');
    for (let d = BIZ_DAYS; d >= 0; d--) {
      const n = ri(4, 9);
      for (let k = 0; k < n; k++) {
        const date = at(d, ri(8, 18), ri(0, 59));
        if (date.getTime() > NOW.getTime()) continue;
        const client = chance(0.75) ? pick(clients) : null;
        const car = client?.cars?.length ? pick(client.cars) : (() => {
          const [marque, model] = pick(CAR_MODELS);
          return { marque, name: model, color: pick(COLORS), immatriculation: `${ri(10000, 99999)} ${ri(110, 124)} 16` };
        })();
        const kindRoll = rnd();
        const kind = kindRoll < 0.55 ? 'lavage' : kindRoll < 0.85 ? 'reparation' : 'mixte';
        const prestations: any[] = [];
        const usedProducts: any[] = [];
        if (kind !== 'reparation') {
          const label = pick(['Lavage extérieur', 'Lavage complet', 'Lavage complet + aspiration', 'Lavage moteur', 'Lustrage']);
          const amount = label === 'Lavage extérieur' ? 500 : label === 'Lavage complet' ? 900 : label === 'Lustrage' ? 2500 : 1200;
          prestations.push({ id: `p-${d}-${k}-l`, kind: 'lavage', label, amount, workerIds: [pick(washers).id] });
        }
        if (kind !== 'lavage') {
          prestations.push({ id: `p-${d}-${k}-v`, kind: 'reparation', label: pick(['Vidange moteur', 'Vidange + filtres', 'Changement filtre à air', 'Vidange boîte']), amount: pick([800, 1000, 1500]), workerIds: [pick(mechanics).id] });
          const oil = pick(oils);
          const qty = oil.unit === 'L' ? ri(4, 6) : 1;
          usedProducts.push({ productId: oil.id, productName: oil.name, qty, unitPrice: oil.salePrice, unitCost: oil.purchasePrice, total: qty * oil.salePrice });
          if (chance(0.7)) {
            const f = pick(filters);
            usedProducts.push({ productId: f.id, productName: f.name, qty: 1, unitPrice: f.salePrice, unitCost: f.purchasePrice, total: f.salePrice });
          }
        }
        const serviceTotal = prestations.reduce((s, p) => s + p.amount, 0);
        const subtotal = serviceTotal + usedProducts.reduce((s, p) => s + p.total, 0);
        const discountAmount = chance(0.08) ? 200 : 0;
        const total = subtotal - discountAmount;
        const pending = d === 0 && chance(0.4);
        const canceled = !pending && chance(0.02);
        const credit = !pending && !canceled && client && chance(0.07);
        const paid = pending || canceled ? 0 : credit ? 0 : total;
        const id = `${px}-rp-${pad(reparations.length + 1, 4)}`;
        reparations.push({
          id, ref: `INT-${pad(reparations.length + 1, 5)}`, kind, clientId: client?.id, clientName: client?.name || 'Client de passage',
          car, serviceTotal, prestations, usedProducts, problem: prestations.map(p => p.label).join(' + '),
          subtotal, discountType: discountAmount ? 'amount' : undefined, discountValue: discountAmount || undefined, discountAmount,
          total, paid, rest: canceled ? 0 : total - paid,
          status: pending ? 'pending' : canceled ? 'canceled' : 'finalized',
          outDate: pending ? undefined : iso(new Date(date.getTime() + 45 * 60_000)), date: iso(date),
          finalizedAt: pending || canceled ? undefined : iso(new Date(date.getTime() + 45 * 60_000)),
          canceledAt: canceled ? iso(date) : undefined,
          workers: [...new Set(prestations.flatMap(p => p.workerIds))], createdBy: cashier.name,
          payrollSettled: d > 20,
        });
      }
    }
    // Percentage workers were paid for the works of last month.
    workers.filter(w => w.salaryType === 'pourcentage').forEach(w => {
      const done = reparations.filter(r => r.payrollSettled && r.status === 'finalized' && r.workers.includes(w.id));
      const worksTotal = done.reduce((s, r) => s + r.prestations.filter((p: any) => p.workerIds.includes(w.id)).reduce((a: number, p: any) => a + p.amount, 0), 0);
      if (!worksTotal) return;
      w.payments.push({
        id: `${w.id}-py-pc`, period: monthKey(new Date(NOW.getFullYear(), NOW.getMonth() - 1, 1)),
        amount: r2(worksTotal * (w.percentage / 100)), date: ymd(at(20, 18)), description: 'Part sur travaux',
        mode: 'Espèces', workIds: done.map(r => r.id), worksTotal, percentage: w.percentage,
      });
    });
    ['Hocine Bennour', 'Passage — Clio grise', 'Ryad Guerfi'].forEach((clientName, i) => {
      const [marque, model] = pick(CAR_MODELS);
      payRequests.push({
        id: `${px}-rq-${i + 1}`, ref: `DEM-${pad(i + 1, 4)}`, clientName,
        car: { marque, name: model, color: pick(COLORS), immatriculation: `${ri(10000, 99999)} ${ri(110, 124)} 16` },
        amount: pick([900, 1200, 2500]), description: pick(['Lavage complet', 'Lavage + aspiration', 'Lustrage']),
        workerId: workers[1].id, workerName: workers[1].name, status: 'pending', createdAt: iso(at(0, Math.max(8, NOW.getHours() - i), 5)),
      });
    });
  }

  // Purchases — restocking in step with what was sold (≈ 35–40 % of sales).
  const purchases: any[] = [];
  const step = isService ? 6 : 3;
  const docValue = (x: any) => Number(x.total) || 0;
  for (let d = BIZ_DAYS; d >= 0; d -= step) {
    const from = at(d, 0).getTime(); const to = at(d - step, 0).getTime();
    const inWindow = (x: any) => { const t = new Date(x.date).getTime(); return t >= from && t < to; };
    const soldValue = sales.filter(inWindow).reduce((s2, x) => s2 + docValue(x), 0)
      + reparations.filter(inWindow).reduce((s2, x) => s2 + docValue(x), 0);
    const target = (d === BIZ_DAYS ? 1.5 : 1) * soldValue * (isService ? 0.3 : 0.38);
    if (target < 2000) continue;
    const sup = pick(suppliers);
    const chosen = sample(products.filter(p => p.purchasePrice > 0), ri(2, 5));
    const lines = chosen.map(p => {
      const qty = Math.max(1, Math.round(target / chosen.length / p.purchasePrice));
      return { productId: p.id, productName: p.name, qty, unitPrice: p.purchasePrice, total: r2(qty * p.purchasePrice), salePrice: p.salePrice };
    });
    const total = r2(lines.reduce((s2, l) => s2 + l.total, 0));
    const paid = d < 8 && chance(0.4) ? Math.round(total * 0.5) : total;
    purchases.push({
      id: `${px}-pu-${pad(purchases.length + 1, 3)}`, ref: `ACH-${px.toUpperCase()}-${pad(purchases.length + 1, 4)}`,
      supplierId: sup.id, supplierName: sup.name, items: lines, total, paid, rest: r2(total - paid),
      date: iso(at(d, 8, ri(0, 50))), createdAt: iso(at(d, 8)), createdBy: cashier.name,
    });
  }

  // Expenses and caisse movements of the part.
  const expenseNames = key === 'restaurant'
    ? [['Gaz butane (bouteilles)', 'Énergie', 1500, 4000], ['Produits d’entretien cuisine', 'Hygiène', 2000, 6000], ['Emballages à emporter', 'Fournitures', 3000, 8000], ['Réparation friteuse', 'Entretien', 4000, 12000], ['Pain complémentaire', 'Achats divers', 800, 2000]]
    : key === 'cafeteria'
      ? [['Gobelets et couvercles', 'Fournitures', 2500, 6000], ['Détartrage machine', 'Entretien', 3000, 7000], ['Produits d’entretien', 'Hygiène', 1500, 4000], ['Sucre en bûchettes', 'Achats divers', 1200, 3000]]
      : [['Réparation aspirateur', 'Entretien', 4000, 11000], ['Chiffons et éponges', 'Fournitures', 1500, 4000], ['Tuyau haute pression', 'Entretien', 6000, 14000], ['Électricité compresseur', 'Énergie', 5000, 9000]];
  const expenses = Array.from({ length: 14 }, (_, i) => {
    const [name, category, min, max] = pick(expenseNames) as [string, string, number, number];
    return {
      id: `${px}-ex-${pad(i + 1, 3)}`, name, description: '', amount: Math.round(rf(min, max) / 50) * 50,
      date: iso(at(ri(0, BIZ_DAYS), ri(9, 17))), category, paymentMode: 'Espèces',
    };
  });
  const caisse = [
    { id: `${px}-cs-001`, type: 'deposit', amount: 20000, date: iso(at(BIZ_DAYS, 8)), description: 'Fonds de caisse', category: 'Fonds' },
    { id: `${px}-cs-002`, type: 'withdraw', amount: 5000, date: iso(at(12, 18)), description: 'Achat urgent marché', category: 'Divers' },
    { id: `${px}-cs-003`, type: 'deposit', amount: 3000, date: iso(at(6, 9)), description: 'Appoint de monnaie', category: 'Fonds' },
  ];

  // Destructions (stock losses).
  const destructionSources = key === 'lavage' ? sellable : [...sellable, ...products.filter(p => p.isRawMaterial)];
  for (let i = 0; i < 5; i++) {
    const p = pick(destructionSources);
    const qty = ri(1, 4);
    destructions.push({
      id: `${px}-ds-${pad(i + 1, 2)}`, source: 'stock', productId: p.id, productName: p.name, categoryName: p.categoryName,
      qty, unit: p.unit, unitPrice: p.salePrice, unitCost: p.purchasePrice, value: r2(qty * p.purchasePrice),
      reason: pick(['Produit périmé', 'Emballage endommagé', 'Casse', 'Produit avarié']), date: iso(at(ri(1, 30), 20)),
      createdBy: cashier.name,
    });
  }

  // Inventaires: one corrected last month, one draft this week.
  const counted = products.slice(0, 10);
  const lines = counted.map(p => {
    const ecart = chance(0.3) ? -ri(1, 3) : chance(0.1) ? 1 : 0;
    return {
      productId: p.id, productName: p.name, categoryId: p.categoryId, categoryName: p.categoryName, unit: p.unit,
      countedQty: Math.max(0, p.currentQty + ecart), purchasePrice: p.purchasePrice, salePrice: p.salePrice,
      systemQtyAtEntry: p.currentQty, _ecart: ecart,
    };
  });
  const ecarts = lines.map(l => ({
    productId: l.productId, productName: l.productName, categoryName: l.categoryName, unit: l.unit,
    countedQty: l.countedQty, systemQty: l.systemQtyAtEntry, ecart: l._ecart, purchasePrice: l.purchasePrice,
    value: r2(l._ecart * l.purchasePrice), kind: l._ecart < 0 ? 'perte' : l._ecart > 0 ? 'gain' : 'exact',
  }));
  const lossLines = ecarts.filter(e => e.ecart < 0);
  const gainLines = ecarts.filter(e => e.ecart > 0);
  const cleanLines = lines.map(({ _ecart, ...l }) => l);
  const inventaires = [
    {
      id: `${px}-iv-001`, ref: `INV-${px.toUpperCase()}-001`, date: ymd(at(25)), status: 'corrected', lines: cleanLines,
      notes: 'Inventaire mensuel', createdAt: iso(at(25, 21)), createdBy: cashier.name, completedAt: iso(at(25, 22)),
      comparison: {
        at: iso(at(25, 22)), by: ADMIN_NAME, lines: ecarts,
        lossQty: -lossLines.reduce((s, e) => s + e.ecart, 0), lossValue: -r2(lossLines.reduce((s, e) => s + e.value, 0)),
        gainQty: gainLines.reduce((s, e) => s + e.ecart, 0), gainValue: r2(gainLines.reduce((s, e) => s + e.value, 0)),
        netValue: r2(ecarts.reduce((s, e) => s + e.value, 0)), productsCounted: lines.length,
        productsWithEcart: ecarts.filter(e => e.ecart !== 0).length,
      },
      correctedAt: iso(at(25, 22, 30)), correctedBy: ADMIN_NAME, chargeWorkers: false,
    },
    {
      id: `${px}-iv-002`, ref: `INV-${px.toUpperCase()}-002`, date: ymd(at(1)), status: 'draft',
      lines: cleanLines.slice(0, 5), notes: 'Comptage en cours', createdAt: iso(at(1, 20)), createdBy: cashier.name,
    },
  ];

  const messageTemplates = isService ? [
    { id: `${px}-mt-1`, name: 'Rappel lavage', usage: 'lavage', createdAt: iso(at(100)), body: 'Bonjour {client}, cela fait un moment que votre {voiture} n’a pas été lavée. Nous vous attendons à la station Altech !' },
    { id: `${px}-mt-2`, name: 'Rappel vidange', usage: 'reparation', createdAt: iso(at(100)), body: 'Bonjour {client}, la vidange de votre {voiture} arrive à échéance. Passez nous voir, sans rendez-vous.' },
    { id: `${px}-mt-3`, name: 'Promotion', usage: 'libre', createdAt: iso(at(60)), body: 'Ce week-end : lavage complet à -20% pour nos clients fidèles !' },
  ] : [];

  // What went in and out of the part's drawer — used to size the bank deposits.
  const sum = (xs: any[], f: (x: any) => number) => xs.reduce((s2, x) => s2 + (f(x) || 0), 0);
  const cashIn = sum(sales.filter(x => x.status !== 'retournée'), x => x.paid)
    + sum(reparations, x => x.paid) + sum(caisse.filter(c => c.type === 'deposit'), c => c.amount);
  const cashOut = sum(purchases, x => x.paid) + sum(expenses, x => x.amount)
    + sum(workers, w => sum(w.payments, (x: any) => x.amount) + sum(w.acomptes, (x: any) => x.amount))
    + sum(caisse.filter(c => c.type === 'withdraw'), c => c.amount);
  const state = {
    categories, marques, roles,
    products: [],
    purchases, sales, clients, suppliers, workers, expenses, caisse,
    productions, fiches, comptoir, destructions, reparations,
    sessions: [],
    payRequests, inventaires, messageTemplates, rappels: [],
    posPinned: (fiches.length ? fiches.slice(0, 4).map((f, i) => `comptoir:${comptoir[i].productName}`) : sellable.slice(0, 4).map(p => `product:${p.id}`)),
    avgCostEnabled: false,
    deletedIds: {},
  };
  return { state, cashIn, cashOut };
}
